#!/bin/bash
echo "Actualisation de la plateforme Altaïr..."
echo "Attention toutes les données personnelles du dossier altair seront effacées."
echo "Veuillez confirmer la poursuite de l'actualisation (Oui/Non)."
echo ""
echo "Oui/Non : "
read reponse
if test x$reponse = xOui; then
   
  git reset --hard HEAD
  git clean -dfx
  adresse=$(cat entrepot.txt)
  git remote remove origin
  git remote add -t Linux origin $adresse
  git pull -X theirs -s recursive origin master

fi

echo "Fin de l'opération."


  
