---
title: "Méthodologie"
output:
  pdf_document:
    number_sections: yes
---

# Eléments méthodologiques sur le calcul des rémunérations
 
Les périmètres retenus sont autant que possibles ajustés pour être proches de ceux du système
d'information sur les agents du service public (SIASP).

L’étude des salaires est réalisée à partir des postes, restreints aux postes actifs et non annexes.

Un certain nombre de différences méthodologiques avec les calculs de l'INSEE et de la DGAFP doivent
toutefois être relevées.

## La caractérisation des postes actifs non annexes

Ces postes se définissent par trois variables : rémunération, nombre d'heures, durée d'emploi.  

On définit tout d'abord une période non annexe.  

Une période est dite non annexe sous les conditions (C) suivantes :   

1. si le salaire net du poste, indépendamment de sa durée, est supérieur à 3 fois le Smic
    mensuel net; ou :  
2. si les trois conditions suivantes sont simultanément remplies :   
    a) la durée du poste est supérieure à 30 jours ;   
    b) le nombre d’heures du poste est supérieur à 120 heures ;  
    c) le nombre d’heures travaillées par jour au cours du poste est supérieur à 1,5 heure.   

Un poste est constitué d’une ou plusieurs périodes de travail d’un salarié dans un même 
établissement.   

On qualifie une période d'active si elle est correspond à un temps complet, à un temps partiel ou à un forfait, à une 
cessation progressive d’activité, à un congé de maladie ordinaire (CMO) ou à un congé formation (CF).   

Sont considérées comme périodes inactives, les rappels, les périodes non rémunérées, les période de chômage,
les congés de fin d’activité (CFA) et les congés longue maladie (CLM).  

Un poste est actif s'il est constitué d'au moins une période active.  

On qualifie un poste de non annexe sous les conditions suivantes :  
1. si le salarié a été rémunéré pour au moins une période non annexe ;   
2. sinon, si les conditions (C) sont vérifiées.   
        
Dans le cas contraire, le poste est dit annexe.   

Pour les calculs réalisés par Altair, les périodes sont systématiquement annuelles ou 
infra-annuelles.  

## Le calcul des quotités   

Les quotités sont calculées exclusivement à partir des postes actifs et non annexes et par la
variable Heures de travail. 

## Les différences avec l'approche du SIASP   

### L'approche par individu  

Dans les fichiers SIASP, l’unité d’intérêt est le poste, ce qui correspond à une ou plusieurs 
périodes de travail d’un salarié dans un même établissement.   

Dans les traitements réalisés pour une seule collectivité simultanément, cette approche ne peut 
être mise en oeuvre, les cas de multi-emplois étant très largement le fait de la combinaison 
d'emplois auprès de plusieurs employeurs publics ou privés.  

L'effet de cette différence de périmètre (qui correspond à celui de l'ancien FGE, Fichier général
des agents de l'Etat) été évalué à +0,3 % par l'INSEE.  

### La caractérisation des postes actifs  

Les postes actifs sont caractéristés de manière plus rudimentaire : les agents actifs sont ceux qui
ont simultanément un nombre d'heures travaillées non nul et un traitement strictement positif.   

En principe ce double critère permet d'exclure les CFA et CLM. Il peut aussi conduire à exclure, à 
tort, des CMO ou des CF de plus d'un mois. Il est estimé que l'impact de cette aproximation reste 
raisonnable à l'échelle de la précision visée. Cette approximation devra faire l'objet d'un examen 
spécifique.  

### L'utilisation de données brutes  

La principale différence avec les traitements réalisés par les services statistiques ministériels
(SSM) a trait a l'absence de redressements pour un certain nombre de variables connues pour leur 
qualité insatisfaisante (grade et statut, nombre d'heures, entre autres). L'impact de l'utilisation
de données brutes, par rapport aux données redressées des SSM, n'est pas évaluable à ce stade.  

### Autres différences et approximations  

A ce stade (novembre 2014), tout mois rémunéré est réputé correspondre à 30 jours de travail, pour 
les critères de caractérisation des périodes et postes annexes du 1.1, plus précisément pour le calcul 
du nombre de jours travaillés et du nombre d’heures travaillées par jour au cours de la période.

Cette approximation est provisoire et sera ultérieurement levée.  

Elle a pour conséquence deux effets contraires : un nombre plus élevé de postes et périodes annexes 
est pris en compte au titre du critère a). Inversement un nombre plus faible de ces postes et périodes
est pris en compte au titre du critère c).

# Références   

Nouveaux compléments méthodologiques suite à l’introduction du système d’information SIASP, INSEE-
DGAFP mars 2013.  

Décompte des emplois et mesure des évolutions de salaires dans les trois versants de la fonction
publique, INSEE-DGAFP novembre 2011.  
 
 
