-- 
--  This is file `test-loader.sub.lua',
--  generated with the docstrip utility.
-- 
--  The original source files were:
-- 
--  luatexbase-loader.dtx  (with options: `testdummy')
--  
--  See the aforementioned source file(s) for copyright and licensing information.
--  
return true
-- 
--  End of File `test-loader.sub.lua'.
