\includegraphics{icones/altair.png}

\hypertarget{logiciel-altair-version-20.08-4}{%
\subsection{Logiciel Altaïr version
20.08-4}\label{logiciel-altair-version-20.08-4}}

\hypertarget{employeur-region-languedoc-roussillon}{%
\subsubsection{Employeur : REGION LANGUEDOC
ROUSSILLON}\label{employeur-region-languedoc-roussillon}}

\hypertarget{siret-23340001900029}{%
\subsubsection{Siret : 23340001900029}\label{siret-23340001900029}}

\hypertarget{etablissement-region-languedoc-roussillon}{%
\subsubsection{Etablissement : REGION LANGUEDOC
ROUSSILLON}\label{etablissement-region-languedoc-roussillon}}

\hypertarget{budget}{%
\subsubsection{Budget :}\label{budget}}

\textbf{Période sous revue : 2015 - 2015 }\\
\textbf{Nombre d'exercices : 1 }

Logiciel sous licence \href{../Docs/LICENCE.html}{CeCILL v.2.1}

dim. 16 août 2020

\textbf{Avertissements}

\emph{1. La production des rapports d'analyse nécessite que les données
de paye soient continues, autrement dit qu'il n'y ait pas d'année ou de
mois manquant dans la série de données disponibles. Lorsque tel est le
cas, il convient de réaliser autant de rapports partiels que de séries
partielles de données continues.}

\emph{2. Il est recommandé de renseigner, dans toute la mesure du
possible, les codes de paye de l'onglet Codes de l'interface graphique}
~
\href{../Docs/Notices/fiche_onglet_codes.odt}{\includegraphics{icones/Notice.png}}

En cas de dysfonctionnement logiciel, veuillez bien signaler les
difficultés rencontrées au développeur.

\hypertarget{statistiques-de-population}{%
\section{1. Statistiques de
population}\label{statistiques-de-population}}

\hypertarget{effectifs}{%
\subsection{1.1 Effectifs}\label{effectifs}}

~\emph{Tableau 1.1.1 : Effectifs}

\begin{longtable}[]{@{}lcc@{}}
\toprule
& Effectifs & 2015\tabularnewline
\midrule
\endhead
1 & Matricules gérés en base (a) & 3 914,0\tabularnewline
2 & ~~~dont présents 12 mois & 3 416,0\tabularnewline
3 & ~~~dont fonctionnaires (b) & 3 225,0\tabularnewline
4 & ~~~dont fonct. présents 12 mois & 3 159,0\tabularnewline
5 & ~~~dont non titulaires & 370,0\tabularnewline
6 & ~~~dont élus & 3,0\tabularnewline
7 & ~~~dont élus présents 12 mois & 3,0\tabularnewline
8 & ~~~dont vacataires détectés (c) & 2,0\tabularnewline
9 & ~~~dont assistantes maternelles détectées (c) & 0,0\tabularnewline
10 & Postes non actifs (g) & 31,0\tabularnewline
11 & Postes actifs annexes (g) & 150,0\tabularnewline
12 & Postes actifs non annexes (g) & 3 730,0\tabularnewline
13 & Total ETP au 31/12 (d) & 3 302,7\tabularnewline
14 & Total ETPT/année (e) & 3 333,6\tabularnewline
15 & Total ETPT/année personnes en place (f)(g) & 0,0\tabularnewline
16 & Total ETPT/année fonctionnaires (g) & 2 911,7\tabularnewline
17 & Total ETPT/année titulaires à temps complet (g) & 2
018,7\tabularnewline
18 & Total ETPT non titulaires (g) & 173,8\tabularnewline
19 & Total ETPT autre statut & 152,0\tabularnewline
20 & Total ETPT postes non actifs (g) & 0,0\tabularnewline
21 & Total ETPT postes actifs annexes (g) & 31,1\tabularnewline
22 & Total ETPT postes actifs non annexes (g) & 3 302,6\tabularnewline
\bottomrule
\end{longtable}

\textbf{Nota:}\\
\emph{(a) Nombre de matricules distincts ayant eu au moins un bulletin
de paie dans l'année, en fonction ou non. Tous ces personnels ne sont
pas en fonction : sont inclus des régularisations, des personnels hors
position d'activité ou des ayants droit (reversion, etc.)}\\
\emph{(b) Titulaires ou stagiaires}\\
\emph{(c) Sur la base des libellés d'emploi et des libellés de lignes de
paie. La détection peut être lacunaire.}\\
\emph{(d) ETP : la quotité est retenue au mois de décembre. Un mi-temps
sur 6 mois compte 0,5.}\\
\emph{(e) ETPT : Equivalent temps plein travaillé = somme des quotités
mensuelles divisée par 12. Un mi-temps sur 6 mois compte 0,25.}\\
\emph{(f) Personnes en place : présentes en N et N-1 avec la même
quotité, postes actifs et non annexes uniquement.}\\
\emph{(g) Postes actifs et non annexes :} voir
\href{../Docs/méthodologie.pdf}{Compléments méthodologiques}\\
\emph{~~~Un poste actif est défini par au moins un bulletin de paie
comportant un traitement positif pour un volume d'heures de travail
mensuel non nul.}\\
\emph{~~~Un poste non annexe est défini comme la conjonction de critères
horaires et de revenu sur une année. La periode minimale de référence
est le mois.}\\
\emph{Les dix dernières lignes du tableau sont calculées en ne tenant
pas compte des élus.}

La durée du travail prise en compte dans la base de données est de
151,61 h par mois.

\href{../Bases/Effectifs/tableau.effectifs.csv}{Lien vers la base des
effectifs}\\
\href{../Bases/Effectifs/tableau.effectifs.grades.csv}{Lien vers la base
des effectifs en ETPT par grade}\\
\href{../Bases/Effectifs/tableau.effectifs.emplois.csv}{Lien vers la base
des effectifs en ETPT par emploi}

\hypertarget{pyramide-des-ages-ensemble-des-personnels}{%
\subsection{1.2 Pyramide des âges, ensemble des
personnels}\label{pyramide-des-ages-ensemble-des-personnels}}

\href{../Docs/Notices/fiche_2.odt}{\includegraphics{icones/Notice.png}}

\includegraphics{altair_files/figure-latex/unnamed-chunk-11-1.png} Error
in sum(Femmes) : `type' (character) de l'argument incorrect La Pyramide
des âges des personnels n'a pas pu être générée.

\href{../Docs/Notices/fiche_3.odt}{\includegraphics{icones/Notice.png}}

\newpage

~\emph{Tableau 1.2.1}

\begin{longtable}[]{@{}ccccc@{}}
\toprule
\begin{minipage}[b]{0.12\columnwidth}\centering
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.29\columnwidth}\centering
Âge des personnels au 31/12/2015\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\centering
Effectif\strut
\end{minipage} & \begin{minipage}[b]{0.29\columnwidth}\centering
Âge des personnels au 31/12/2015\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\centering
Effectif\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.12\columnwidth}\centering
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
20,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
20,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
41,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
41,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
48,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
48,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
46,7\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
3444\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
46,7\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
3444\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
54,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
54,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
78,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
78,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\href{../Docs/Notices/fiche_1.odt}{\includegraphics{icones/Notice.png}}

\hypertarget{pyramide-des-ages-des-fonctionnaires}{%
\subsection{1.3 Pyramide des âges des fonctionnaires
~}\label{pyramide-des-ages-des-fonctionnaires}}

\href{../Docs/Notices/fiche_2.odt}{\includegraphics{icones/Notice.png}}

\includegraphics{altair_files/figure-latex/unnamed-chunk-17-1.png}
\includegraphics{altair_files/figure-latex/unnamed-chunk-17-2.png} Pour
obtenir les effectifs nationaux, multiplier les abscisses des hommes par
351 et les abscisses des femmes par 134\newpage Le graphique des
variations d'effectifs par tranche d'âge ne peut être produit.

\href{../Docs/Notices/fiche_3.odt}{\includegraphics{icones/Notice.png}}

\newpage

~\emph{Tableau 1.3.1}

\begin{longtable}[]{@{}ccccc@{}}
\toprule
\begin{minipage}[b]{0.12\columnwidth}\centering
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.29\columnwidth}\centering
Âge des personnels au 31/12/2015\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\centering
Effectif\strut
\end{minipage} & \begin{minipage}[b]{0.29\columnwidth}\centering
Âge des personnels au 31/12/2015\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\centering
Effectif\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.12\columnwidth}\centering
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
20,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
20,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
42,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
42,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
48,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
48,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
47,4\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
3125\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
47,4\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
3125\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
54,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
54,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
67,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
67,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Effectifs/Pyramide-des-ages-des-fonctionnaires_2015.csv}{Lien
vers la base des âges - début de periode}

\href{../Bases/Effectifs/Pyramide-des-ages-des-fonctionnaires_2015.csv}{Lien
vers la base des âges - fin de periode}

\href{../Docs/Notices/fiche_1.odt}{\includegraphics{icones/Notice.png}}

\hypertarget{pyramide-des-ages-personnels-non-titulaires}{%
\subsection{1.4 Pyramide des âges, personnels non titulaires
~}\label{pyramide-des-ages-personnels-non-titulaires}}

\href{../Docs/Notices/fiche_2.odt}{\includegraphics{icones/Notice.png}}

\includegraphics{altair_files/figure-latex/unnamed-chunk-23-1.png}
\includegraphics{altair_files/figure-latex/unnamed-chunk-23-2.png} Pour
obtenir les effectifs nationaux, multiplier les abscisses des hommes par
2 214 et les abscisses des femmes par 462\newpage Le graphique des
variations d'effectifs par tranche d'âge ne peut être produit.

\href{../Docs/Notices/fiche_3.odt}{\includegraphics{icones/Notice.png}}

\newpage

~\emph{Tableau 1.4.1}

\begin{longtable}[]{@{}ccccc@{}}
\toprule
\begin{minipage}[b]{0.12\columnwidth}\centering
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.29\columnwidth}\centering
Âge des personnels au 31/12/2015\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\centering
Effectif\strut
\end{minipage} & \begin{minipage}[b]{0.29\columnwidth}\centering
Âge des personnels au 31/12/2015\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\centering
Effectif\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.12\columnwidth}\centering
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
21,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
21,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
32,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
32,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
39,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
39,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
39,1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
203\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
39,1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
203\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
47,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
47,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
64,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
64,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Effectifs/Pyramide-des-ages-des-non-titulaires_2015.csv}{Lien
vers la base des âges - début de periode}

\href{../Bases/Effectifs/Pyramide-des-ages-des-non-titulaires_2015.csv}{Lien
vers la base des âges - fin de periode}

\href{../Docs/Notices/fiche_1.odt}{\includegraphics{icones/Notice.png}}

\hypertarget{pyramide-des-ages-autres-statuts}{%
\subsection{1.5 Pyramide des âges, autres statuts
~}\label{pyramide-des-ages-autres-statuts}}

\href{../Docs/Notices/fiche_2.odt}{\includegraphics{icones/Notice.png}}

\includegraphics{altair_files/figure-latex/unnamed-chunk-29-1.png}
\newpage Le graphique des variations d'effectifs par tranche d'âge ne
peut être produit.

\href{../Docs/Notices/fiche_3.odt}{\includegraphics{icones/Notice.png}}

\newpage

~\emph{Tableau 1.5.1}

\begin{longtable}[]{@{}ccccc@{}}
\toprule
\begin{minipage}[b]{0.12\columnwidth}\centering
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.29\columnwidth}\centering
Âge des personnels au 31/12/2015\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\centering
Effectif\strut
\end{minipage} & \begin{minipage}[b]{0.29\columnwidth}\centering
Âge des personnels au 31/12/2015\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\centering
Effectif\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.12\columnwidth}\centering
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
20,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
20,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
26,8\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
26,8\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
39,5\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
39,5\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
41,1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
116\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
41,1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
116\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
54,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
54,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\centering
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
78,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\centering
78,0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\centering
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Effectifs/Pyramide-des-ages-des-autres-personnels_2015.csv}{Lien
vers la base des âges - début de periode}

\href{../Bases/Effectifs/Pyramide-des-ages-des-autres-personnels_2015.csv}{Lien
vers la base des âges - fin de periode}

\href{../Docs/Notices/fiche_1.odt}{\includegraphics{icones/Notice.png}}

\emph{Source des comparaisons avec les données nationales}

Rapport annuel sur l'état de la fonction publique pour 2016\\
\href{../Docs/insee_pyramide_fph_2013.csv}{Pyramide 2013 FPH}\\
\href{../Docs/insee_pyramide_fpt_2013.csv}{Pyramide 2013 FPT}\\
\emph{Toutes les pyramides des âges sont établies au 31 décembre de
l'annee considérée.}\\
\emph{Les élus ne sont pas compris dans le périmètre statistique.}

\hypertarget{effectifs-des-personnels-par-duree-de-service}{%
\subsection{1.6 Effectifs des personnels par duree de
service}\label{effectifs-des-personnels-par-duree-de-service}}

\textbf{Personnels en fonction (hors élus) des exercices 2015 à 2015
inclus :}

~\emph{Tableau 1.6.1}

\begin{longtable}[]{@{}cccc@{}}
\toprule
Plus de 2 ans & Moins de 2 ans & Moins d'un an & Moins de six
mois\tabularnewline
\midrule
\endhead
3 109 & 621 & 331 & 90\tabularnewline
\bottomrule
\end{longtable}

\textbf{Effectifs (hors élus)}

~\emph{Tableau 1.6.2}

\begin{longtable}[]{@{}lc@{}}
\toprule
& 2015\tabularnewline
\midrule
\endhead
Plus de deux ans & 3 109\tabularnewline
Moins de deux ans & 621\tabularnewline
Total & 3 730\tabularnewline
\bottomrule
\end{longtable}

\textbf{Nota :} \emph{Personnels en place : ayant servi au moins deux
années consécutives pendant la periode.}\\
\emph{Plus/moins de deux ans : plus/mois de 730 jours sur la periode
sous revue.}

\hypertarget{remunerations-brutes-analyse-pour-le-premier-exercice}{%
\section{2. Rémunérations brutes : analyse pour le premier
exercice}\label{remunerations-brutes-analyse-pour-le-premier-exercice}}

\textbf{Exercice : 2015 }

\hypertarget{remunerations-brutes-de-lensemble-des-agents}{%
\subsection{2.1 Rémunérations brutes de l'ensemble des
agents}\label{remunerations-brutes-de-lensemble-des-agents}}

\textbf{Cumuls des rémunérations brutes pour l'exercice 2015 }

\emph{Personnels (hors élus)}

~\emph{Tableau 2.1.1}

\begin{longtable}[]{@{}ll@{}}
\toprule
Agrégats & k€\tabularnewline
\midrule
\endhead
Brut annuel (bulletins) & 170 602 458,6\tabularnewline
Brut annuel (lignes) : & 170 688 630,4\tabularnewline
~dont ~Primes : & 33 871 375,1\tabularnewline
~dont ~Autres rémunérations &\tabularnewline
Part de primes en \% & 19,9\tabularnewline
\bottomrule
\end{longtable}

\textbf{Définitions :}

\emph{Brut annuel (bulletins)} : somme du champ \emph{Brut}\\
\emph{Brut annuel (lignes)} : somme du champ \emph{Montant} des lignes
de paye, dont :\\
\emph{Primes} : indemnités sauf remboursements, certaines IJSS,
indemnités d'élu le cas échéant, Supplément familial de traitement et
Indemnité de résidence\\
\emph{Autres rémunérations} : acomptes, retenues sur brut, rémunérations
diverses, rappels

\textbf{Tests de cohérence}

Somme des rémunérations brutes versées aux personnels (non élus) :

~\emph{Tableau 2.1.2}

\begin{longtable}[]{@{}ll@{}}
\toprule
Agrégats & k€\tabularnewline
\midrule
\endhead
Bulletins de paie & 170 602 458,6\tabularnewline
Lignes de paie & 170 688 630,4\tabularnewline
Difference & -86 171,9\tabularnewline
\bottomrule
\end{longtable}

à comparer aux soldes des comptes 641 et 648 du compte de gestion.

\hypertarget{remunerations-brutes-des-fonctionnaires}{%
\subsection{2.2 Rémunérations brutes des
fonctionnaires}\label{remunerations-brutes-des-fonctionnaires}}

\emph{Cette section concerne les personnels fonctionnaires titulaires et
stagiaires}

\includegraphics{altair_files/figure-latex/unnamed-chunk-43-1.png}

\includegraphics{altair_files/figure-latex/unnamed-chunk-43-2.png}

\includegraphics{altair_files/figure-latex/unnamed-chunk-43-3.png}

\includegraphics{altair_files/figure-latex/unnamed-chunk-43-4.png}

\includegraphics{altair_files/figure-latex/unnamed-chunk-43-5.png}

\includegraphics{altair_files/figure-latex/unnamed-chunk-43-6.png}

\textbf{Nota :}\\
\emph{Cet histogramme décrit l'évolution de la rémunération moyenne des
personnes en place (RMPP), définies comme présentes deux annees entières
consécutives avec la même quotité}\\
\emph{L'évolution de la RMPP permet d'étudier le glissement
vieillesse-technicité ``positif'', à effectifs constants sur deux
années}

\textbf{Effectif : 3083 }

\textbf{Tests de cohérence}

Somme des rémunérations brutes versées aux personnels titulaires et
stagiaires :

~\emph{Tableau 2.2.1}

\begin{longtable}[]{@{}ll@{}}
\toprule
Agrégats & k€\tabularnewline
\midrule
\endhead
Brut annuel (bulletins) & 150 687 370,5\tabularnewline
Brut annuel (lignes) : & 150 743 771,4\tabularnewline
~dont ~~primes : & 30 845 615,3\tabularnewline
~dont ~autres rémunérations : &\tabularnewline
Part de primes en \% & 20,5\tabularnewline
\bottomrule
\end{longtable}

\textbf{Définitions :}

\emph{Brut annuel (bulletins)} : somme du champ \emph{Brut}\\
\emph{Brut annuel (lignes)} : somme du champ \emph{Montant} des lignes
de paye, dont :\\
\emph{Primes} : indemnités sauf remboursements, certaines IJSS,
Supplément familial de traitement et Indemnité de résidence\\
\emph{Autres rémunérations} : acomptes, retenues sur brut, rémunérations
diverses, rappels

\textbf{Tests de cohérence}

Somme des rémunérations brutes versées aux personnels (fonctionnaires) :

~\emph{Tableau 2.2.2}

\begin{longtable}[]{@{}ll@{}}
\toprule
Agrégats & k€\tabularnewline
\midrule
\endhead
Bulletins de paie & 150 687 370,5\tabularnewline
Lignes de paie & 150 743 771,4\tabularnewline
Difference & -56 400,9\tabularnewline
\bottomrule
\end{longtable}

A comparer aux soldes des comptes 6411, 6419 et 648 du compte de
gestion.

\textbf{Formation et distribution du salaire brut moyen par tête (SMPT)
en EQTP pour l'annee 2015 }

~\emph{Tableau 2.2.3}

\begin{longtable}[]{@{}rrrrrr@{}}
\toprule
\begin{minipage}[b]{0.14\columnwidth}\raggedleft
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.23\columnwidth}\raggedleft
Traitement indiciaire\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
Primes\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Autres rémunérations\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Quotité\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\raggedleft
Effectif\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
4 848\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0,25\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
36 194\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
6 110\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
36 811\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
6 473\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
39 733\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
10 173\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1,9\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
3069\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
41 385\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
10 788\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
122 425\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
80 375\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 2.2.4}

\begin{longtable}[]{@{}rrrrrrr@{}}
\toprule
\begin{minipage}[b]{0.11\columnwidth}\raggedleft
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Total lignes hors rappels\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\raggedleft
Total brut\strut
\end{minipage} & \begin{minipage}[b]{0.14\columnwidth}\raggedleft
SMPT brut en EQTP\strut
\end{minipage} & \begin{minipage}[b]{0.14\columnwidth}\raggedleft
Part indemnitaire\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\raggedleft
Quotité\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
Effectif\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
5 186\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
5 186\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
4 882\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
0,25\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
42 417\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
42 406\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
21 366\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
14\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
44 594\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
44 587\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
22 848\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
15\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
49 923\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
49 905\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
25 913\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
19\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1,9\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
3069\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
49 995\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
49 986\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
25 718\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
22\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
199 877\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
199 877\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
100 000\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
100\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emph{Hors vacataires identifiés, assistantes maternelles, élus locaux
et pour les postes actifs non annexes}

\textbf{Categorie A}

~\emph{Tableau 2.2.5}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
Statistique & Traitement indiciaire & Primes & Autres rémunérations &
Quotité\tabularnewline
\midrule
\endhead
Minimum & 6 964 & 2 514 & 0 & 0,29\tabularnewline
1er quartile & 50 063 & 21 276 & 0 & 2\tabularnewline
Médiane & 57 899 & 26 702 & 0 & 2\tabularnewline
Moyenne & 59 317 & 30 548 & 0 & 1,9\tabularnewline
3ème quartile & 67 454 & 35 304 & 0 & 2\tabularnewline
Maximum & 122 425 & 80 375 & 0 & 2\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 2.2.6}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
\begin{minipage}[b]{0.14\columnwidth}\raggedleft
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Total rémunérations\strut
\end{minipage} & \begin{minipage}[b]{0.25\columnwidth}\raggedleft
Total rémunérations EQTP\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\raggedleft
Part indemnitaire\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Quotité\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
10 263\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
19 540\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
6,4\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0,29\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
71 689\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
37 764\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
29\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
85 807\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
44 889\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
32\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
89 935\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
47 016\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
33\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1,9\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
105 857\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
54 283\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
37\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
199 877\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
100 000\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
49\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{Effectif : 330 }

\textbf{Categorie B}

~\emph{Tableau 2.2.7}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
Statistique & Traitement indiciaire & Primes & Autres rémunérations &
Quotité\tabularnewline
\midrule
\endhead
Minimum & 16 623 & 6 218 & 0 & 0,67\tabularnewline
1er quartile & 41 274 & 14 017 & 0 & 2\tabularnewline
Médiane & 46 278 & 14 887 & 0 & 2\tabularnewline
Moyenne & 46 690 & 15 800 & 0 & 1,9\tabularnewline
3ème quartile & 52 007 & 17 847 & 0 & 2\tabularnewline
Maximum & 67 843 & 26 872 & 0 & 2\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 2.2.8}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
\begin{minipage}[b]{0.12\columnwidth}\raggedleft
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Total rémunérations\strut
\end{minipage} & \begin{minipage}[b]{0.21\columnwidth}\raggedleft
Total rémunérations EQTP\strut
\end{minipage} & \begin{minipage}[b]{0.31\columnwidth}\raggedleft
Part de la rémunération indemnitaire\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
Quotité\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
22 705\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
19 940\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
16\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
0,67\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
55 936\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
29 422\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
23\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
62 010\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
31 894\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
25\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
62 854\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
33 000\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
25\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
1,9\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
67 334\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
35 528\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
27\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
129 538\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
74 378\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
43\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{Effectif : 162 }

\textbf{Categorie C}

~\emph{Tableau 2.2.9}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
Statistique & Traitement indiciaire & Primes & Autres rémunérations &
Quotité\tabularnewline
\midrule
\endhead
Minimum & 8 301 & 0 & 0 & 0,43\tabularnewline
1er quartile & 36 116 & 5 949 & 0 & 2\tabularnewline
Médiane & 36 561 & 6 308 & 0 & 2\tabularnewline
Moyenne & 36 880 & 7 336 & 0 & 1,9\tabularnewline
3ème quartile & 38 450 & 7 952 & 0 & 2\tabularnewline
Maximum & 60 748 & 23 077 & 0 & 2\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 2.2.10}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
\begin{minipage}[b]{0.12\columnwidth}\raggedleft
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Total rémunérations\strut
\end{minipage} & \begin{minipage}[b]{0.21\columnwidth}\raggedleft
Total rémunérations EQTP\strut
\end{minipage} & \begin{minipage}[b]{0.31\columnwidth}\raggedleft
Part de la rémunération indemnitaire\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
Quotité\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
7 303\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
4 882\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
0,43\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
42 274\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
21 275\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
14\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
43 616\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
22 324\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
15\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
44 184\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
22 883\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
17\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
1,9\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
47 130\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
24 099\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
18\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
107 707\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
53 854\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
100\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{Effectif : 2576 }

\hypertarget{contractuels-vacataires-et-stagiaires-inclus}{%
\subsection{2.3 Contractuels, vacataires et stagiaires
inclus}\label{contractuels-vacataires-et-stagiaires-inclus}}

\emph{Les assistantes maternelles et les vacataires sont ici inclus,
pour les postes non annexes}

\includegraphics{altair_files/figure-latex/unnamed-chunk-61-1.png}

\textbf{Nota :} Ne sont retenues que les rémunérations supérieures à 1
000 k€. Les élus ne sont pas pris en compte.

\textbf{Formation et distribution du salaire brut moyen par tête (SMPT)
en EQTP pour l'année 2015 }

~\emph{Tableau 2.3.1}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
Statistique & Primes & Autres rémunérations & Quotité &
Effectif\tabularnewline
\midrule
\endhead
Minimum & 0 & 0 & 0,31 &\tabularnewline
1er quartile & 73 & 0 & 1,3 &\tabularnewline
Médiane & 1 190 & 0 & 1,7 &\tabularnewline
Moyenne & 7 027 & 0 & 1,5 & 661\tabularnewline
3ème quartile & 6 680 & 0 & 2 &\tabularnewline
Maximum & 164 436 & 0 & 2 &\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 2.3.2}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
Statistique & Total rémunérations & Total rémunérations EQTP & Quotité &
Effectif\tabularnewline
\midrule
\endhead
Minimum & 2 774 & 8 471 & 0,31 &\tabularnewline
1er quartile & 24 936 & 17 861 & 1,3 &\tabularnewline
Médiane & 30 827 & 18 924 & 1,7 &\tabularnewline
Moyenne & 41 840 & 25 076 & 1,5 & 661\tabularnewline
3ème quartile & 44 518 & 23 025 & 2 &\tabularnewline
Maximum & 306 376 & 153 188 & 2 &\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Remunerations/Analyse.remunerations.csv}{Lien vers la base
des rémunérations}

\newpage

\hypertarget{remunerations-brutes-analyse-pour-le-dernier-exercice}{%
\section{3. Rémunérations brutes : analyse pour le dernier
exercice}\label{remunerations-brutes-analyse-pour-le-dernier-exercice}}

\textbf{Exercice : 2015 }

\hypertarget{remunerations-brutes-de-lensemble-des-agents-1}{%
\subsection{3.1 Rémunérations brutes de l'ensemble des
agents}\label{remunerations-brutes-de-lensemble-des-agents-1}}

\textbf{Cumuls des rémunérations brutes pour l'exercice 2015 }

\emph{Personnels (hors élus)}

~\emph{Tableau 3.1.1}

\begin{longtable}[]{@{}ll@{}}
\toprule
Agrégats & k€\tabularnewline
\midrule
\endhead
Brut annuel (bulletins) & 170 602 458,6\tabularnewline
Brut annuel (lignes) : & 170 688 630,4\tabularnewline
~dont ~Primes : & 33 871 375,1\tabularnewline
~dont ~Autres rémunérations &\tabularnewline
Part de primes en \% & 19,9\tabularnewline
\bottomrule
\end{longtable}

\textbf{Définitions :}

\emph{Brut annuel (bulletins)} : somme du champ \emph{Brut}\\
\emph{Brut annuel (lignes)} : somme du champ \emph{Montant} des lignes
de paye, dont :\\
\emph{Primes} : indemnités sauf remboursements, certaines IJSS,
indemnités d'élu le cas échéant, Supplément familial de traitement et
Indemnité de résidence\\
\emph{Autres rémunérations} : acomptes, retenues sur brut, rémunérations
diverses, rappels

\textbf{Tests de cohérence}

Somme des rémunérations brutes versées aux personnels (non élus) :

~\emph{Tableau 3.1.2}

\begin{longtable}[]{@{}ll@{}}
\toprule
Agrégats & k€\tabularnewline
\midrule
\endhead
Bulletins de paie & 170 602 458,6\tabularnewline
Lignes de paie & 170 688 630,4\tabularnewline
Difference & -86 171,9\tabularnewline
\bottomrule
\end{longtable}

à comparer aux soldes des comptes 641 et 648 du compte de gestion.

\hypertarget{remunerations-brutes-des-fonctionnaires-1}{%
\subsection{3.2 Rémunérations brutes des
fonctionnaires}\label{remunerations-brutes-des-fonctionnaires-1}}

\emph{Cette section concerne les personnels fonctionnaires titulaires et
stagiaires}

\includegraphics{altair_files/figure-latex/unnamed-chunk-76-1.png}

\includegraphics{altair_files/figure-latex/unnamed-chunk-76-2.png}

\includegraphics{altair_files/figure-latex/unnamed-chunk-76-3.png}

\includegraphics{altair_files/figure-latex/unnamed-chunk-76-4.png}

\includegraphics{altair_files/figure-latex/unnamed-chunk-76-5.png}

\includegraphics{altair_files/figure-latex/unnamed-chunk-76-6.png}

\textbf{Nota :}\\
\emph{Cet histogramme décrit l'évolution de la rémunération moyenne des
personnes en place (RMPP), définies comme présentes deux annees entières
consécutives avec la même quotité}\\
\emph{L'évolution de la RMPP permet d'étudier le glissement
vieillesse-technicité ``positif'', à effectifs constants sur deux
années}

\textbf{Effectif : 3083 }

\textbf{Tests de cohérence}

Somme des rémunérations brutes versées aux personnels titulaires et
stagiaires :

~\emph{Tableau 3.2.1}

\begin{longtable}[]{@{}ll@{}}
\toprule
Agrégats & k€\tabularnewline
\midrule
\endhead
Brut annuel (bulletins) & 150 687 370,5\tabularnewline
Brut annuel (lignes) : & 150 743 771,4\tabularnewline
~dont ~~primes : & 30 845 615,3\tabularnewline
~dont ~autres rémunérations : &\tabularnewline
Part de primes en \% & 20,5\tabularnewline
\bottomrule
\end{longtable}

\textbf{Définitions :}

\emph{Brut annuel (bulletins)} : somme du champ \emph{Brut}\\
\emph{Brut annuel (lignes)} : somme du champ \emph{Montant} des lignes
de paye, dont :\\
\emph{Primes} : indemnités sauf remboursements, certaines IJSS,
Supplément familial de traitement et Indemnité de résidence\\
\emph{Autres rémunérations} : acomptes, retenues sur brut, rémunérations
diverses, rappels

\textbf{Tests de cohérence}

Somme des rémunérations brutes versées aux personnels (fonctionnaires) :

~\emph{Tableau 3.2.2}

\begin{longtable}[]{@{}ll@{}}
\toprule
Agrégats & k€\tabularnewline
\midrule
\endhead
Bulletins de paie & 150 687 370,5\tabularnewline
Lignes de paie & 150 743 771,4\tabularnewline
Difference & -56 400,9\tabularnewline
\bottomrule
\end{longtable}

A comparer aux soldes des comptes 6411, 6419 et 648 du compte de
gestion.

\textbf{Formation et distribution du salaire brut moyen par tête (SMPT)
en EQTP pour l'année 2015 }

~\emph{Tableau 3.2.3}

\begin{longtable}[]{@{}rrrrrr@{}}
\toprule
\begin{minipage}[b]{0.14\columnwidth}\raggedleft
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.23\columnwidth}\raggedleft
Traitement indiciaire\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
Primes\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Autres rémunérations\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Quotité\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\raggedleft
Effectif\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
4 848\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0,25\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
36 194\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
6 110\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
36 811\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
6 473\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
39 733\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
10 173\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1,9\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
3069\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
41 385\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
10 788\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.23\columnwidth}\raggedleft
122 425\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
80 375\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 3.2.4}

\begin{longtable}[]{@{}rrrrrrr@{}}
\toprule
\begin{minipage}[b]{0.11\columnwidth}\raggedleft
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Total lignes hors rappels\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\raggedleft
Total brut\strut
\end{minipage} & \begin{minipage}[b]{0.14\columnwidth}\raggedleft
SMPT brut en EQTP\strut
\end{minipage} & \begin{minipage}[b]{0.14\columnwidth}\raggedleft
Part indemnitaire\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\raggedleft
Quotité\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
Effectif\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
5 186\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
5 186\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
4 882\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
0,25\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
42 417\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
42 406\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
21 366\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
14\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
44 594\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
44 587\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
22 848\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
15\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
49 923\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
49 905\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
25 913\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
19\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1,9\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
3069\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
49 995\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
49 986\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
25 718\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
22\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.11\columnwidth}\raggedleft
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
199 877\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
199 877\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
100 000\strut
\end{minipage} & \begin{minipage}[t]{0.14\columnwidth}\raggedleft
100\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emph{Hors vacataires identifiés, assistantes maternelles, élus locaux
et pour les postes actifs non annexes}

\textbf{Categorie A}

~\emph{Tableau 3.2.5}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
Statistique & Traitement indiciaire & Primes & Autres rémunérations &
Quotité\tabularnewline
\midrule
\endhead
Minimum & 6 964 & 2 514 & 0 & 0,29\tabularnewline
1er quartile & 50 063 & 21 276 & 0 & 2\tabularnewline
Médiane & 57 899 & 26 702 & 0 & 2\tabularnewline
Moyenne & 59 317 & 30 548 & 0 & 1,9\tabularnewline
3ème quartile & 67 454 & 35 304 & 0 & 2\tabularnewline
Maximum & 122 425 & 80 375 & 0 & 2\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 3.2.6}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
\begin{minipage}[b]{0.14\columnwidth}\raggedleft
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.20\columnwidth}\raggedleft
Total rémunérations\strut
\end{minipage} & \begin{minipage}[b]{0.25\columnwidth}\raggedleft
Total rémunérations EQTP\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\raggedleft
Part indemnitaire\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Quotité\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
10 263\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
19 540\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
6,4\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
0,29\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
71 689\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
37 764\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
29\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
85 807\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
44 889\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
32\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
89 935\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
47 016\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
33\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
1,9\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
105 857\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
54 283\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
37\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.14\columnwidth}\raggedleft
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.20\columnwidth}\raggedleft
199 877\strut
\end{minipage} & \begin{minipage}[t]{0.25\columnwidth}\raggedleft
100 000\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\raggedleft
49\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{Effectif : 330 }

\textbf{Categorie B}

~\emph{Tableau 3.2.7}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
Statistique & Traitement indiciaire & Primes & Autres rémunérations &
Quotité\tabularnewline
\midrule
\endhead
Minimum & 16 623 & 6 218 & 0 & 0,67\tabularnewline
1er quartile & 41 274 & 14 017 & 0 & 2\tabularnewline
Médiane & 46 278 & 14 887 & 0 & 2\tabularnewline
Moyenne & 46 690 & 15 800 & 0 & 1,9\tabularnewline
3ème quartile & 52 007 & 17 847 & 0 & 2\tabularnewline
Maximum & 67 843 & 26 872 & 0 & 2\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 3.2.8}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
\begin{minipage}[b]{0.12\columnwidth}\raggedleft
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Total rémunérations\strut
\end{minipage} & \begin{minipage}[b]{0.21\columnwidth}\raggedleft
Total rémunérations EQTP\strut
\end{minipage} & \begin{minipage}[b]{0.31\columnwidth}\raggedleft
Part de la rémunération indemnitaire\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
Quotité\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
22 705\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
19 940\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
16\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
0,67\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
55 936\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
29 422\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
23\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
62 010\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
31 894\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
25\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
62 854\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
33 000\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
25\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
1,9\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
67 334\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
35 528\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
27\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
129 538\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
74 378\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
43\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{Effectif : 162 }

\textbf{Categorie C}

~\emph{Tableau 3.2.9}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
Statistique & Traitement indiciaire & Primes & Autres rémunérations &
Quotité\tabularnewline
\midrule
\endhead
Minimum & 8 301 & 0 & 0 & 0,43\tabularnewline
1er quartile & 36 116 & 5 949 & 0 & 2\tabularnewline
Médiane & 36 561 & 6 308 & 0 & 2\tabularnewline
Moyenne & 36 880 & 7 336 & 0 & 1,9\tabularnewline
3ème quartile & 38 450 & 7 952 & 0 & 2\tabularnewline
Maximum & 60 748 & 23 077 & 0 & 2\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 3.2.10}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
\begin{minipage}[b]{0.12\columnwidth}\raggedleft
Statistique\strut
\end{minipage} & \begin{minipage}[b]{0.17\columnwidth}\raggedleft
Total rémunérations\strut
\end{minipage} & \begin{minipage}[b]{0.21\columnwidth}\raggedleft
Total rémunérations EQTP\strut
\end{minipage} & \begin{minipage}[b]{0.31\columnwidth}\raggedleft
Part de la rémunération indemnitaire\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
Quotité\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Minimum\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
7 303\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
4 882\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
0,43\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
1er quartile\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
42 274\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
21 275\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
14\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Médiane\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
43 616\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
22 324\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
15\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Moyenne\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
44 184\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
22 883\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
17\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
1,9\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
3ème quartile\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
47 130\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
24 099\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
18\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.12\columnwidth}\raggedleft
Maximum\strut
\end{minipage} & \begin{minipage}[t]{0.17\columnwidth}\raggedleft
107 707\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
53 854\strut
\end{minipage} & \begin{minipage}[t]{0.31\columnwidth}\raggedleft
100\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
2\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{Effectif : 2576 }

\hypertarget{contractuels-vacataires-et-stagiaires-inclus-1}{%
\subsection{3.3 Contractuels, vacataires et stagiaires
inclus}\label{contractuels-vacataires-et-stagiaires-inclus-1}}

\emph{Les assistantes maternelles et les vacataires sont ici inclus,
pour les postes non annexes}

\includegraphics{altair_files/figure-latex/unnamed-chunk-94-1.png}

\textbf{Nota :} Ne sont retenues que les rémunérations supérieures à 1
000 k€. Les élus ne sont pas pris en compte.

\textbf{Formation et distribution du salaire brut moyen par tête (SMPT)
en EQTP pour l'année 2015 }

~\emph{Tableau 3.3.1}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
Statistique & Primes & Autres rémunérations & Quotité &
Effectif\tabularnewline
\midrule
\endhead
Minimum & 0 & 0 & 0,31 &\tabularnewline
1er quartile & 73 & 0 & 1,3 &\tabularnewline
Médiane & 1 190 & 0 & 1,7 &\tabularnewline
Moyenne & 7 027 & 0 & 1,5 & 661\tabularnewline
3ème quartile & 6 680 & 0 & 2 &\tabularnewline
Maximum & 164 436 & 0 & 2 &\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 3.3.2}

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
Statistique & Total rémunérations & Total rémunérations EQTP & Quotité &
Effectif\tabularnewline
\midrule
\endhead
Minimum & 2 774 & 8 471 & 0,31 &\tabularnewline
1er quartile & 24 936 & 17 861 & 1,3 &\tabularnewline
Médiane & 30 827 & 18 924 & 1,7 &\tabularnewline
Moyenne & 41 840 & 25 076 & 1,5 & 661\tabularnewline
3ème quartile & 44 518 & 23 025 & 2 &\tabularnewline
Maximum & 306 376 & 153 188 & 2 &\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Remunerations/Analyse.remunerations.csv}{Lien vers la base
des rémunérations}

\newpage

\hypertarget{remunerations-brutes-par-grade-et-par-emploi}{%
\subsection{3.4 Rémunérations brutes par grade et par
emploi}\label{remunerations-brutes-par-grade-et-par-emploi}}

\href{../Bases/Remunerations/brut.eqtp.csv}{Rémunérations brutes par grade}

\href{../Bases/Remunerations/brut.eqtp.emploi.csv}{Rémunérations brutes par
emploi}

\hypertarget{comparaisons-source-inseedgcl}{%
\subsection{3.5 Comparaisons source
INSEE/DGCL}\label{comparaisons-source-inseedgcl}}

\emph{Salaires annnuels bruts moyens 2011-2017 en EQTP (hors assistantes
maternelles)}

~\emph{Tableau 3.5.1}

\begin{longtable}[]{@{}llllllll@{}}
\toprule
Agrégat (euros) & 2011 & 2012 & 2013 & 2014 & 2015 & 2016 &
2017\tabularnewline
\midrule
\endhead
Ensemble & 25 908 & 26 340 & 26 616 & 26 844 & 27 384 & 27 636 & 28
356\tabularnewline
Titulaires & 26 676 & 27 108 & 27 444 & 28 044 & 28 464 & 28 764 & 29
472\tabularnewline
Autres salariés* & 22 836 & NA & 24 360 & 24 504 & 24 696 & 24 828 & 25
320\tabularnewline
\bottomrule
\end{longtable}

\begin{itemize}
\tightlist
\item
  \emph{Contractuels à partir de 2017} *
\end{itemize}

\textbf{Eléments de la rémunération brute pour les titulaires de la
fonction publique territoriale}

~\emph{Tableau 3.5.2}

\begin{longtable}[]{@{}lllllll@{}}
\toprule
Rém. annuelles & 2011 & Primes & 2012 & Primes & 2013 &
Primes\tabularnewline
\midrule
\endhead
Salaire brut & 26 660 & & 27 108 & & 27 444 &\tabularnewline
Traitement brut & 20 562 & 22,9 \% & 20 724 & 23,6 \% & 21 060 & 23,6
\%\tabularnewline
Primes et rémunérations annexes & & & & & &\tabularnewline
y compris IR et SFT & 6 098 & & 6 384 & & 6 384 &\tabularnewline
\bottomrule
\end{longtable}

\begin{longtable}[]{@{}lllllll@{}}
\toprule
Rém. annuelles & 2014 & Primes & 2015 & Primes & 2016 &
Primes\tabularnewline
\midrule
\endhead
Salaire brut & 28 044 & & 28 464 & & 28 764 &\tabularnewline
Traitement brut & 21 456 & 23,5 \% & 21 816 & 23,4 \% & 22 104 & 23,2
\%\tabularnewline
Primes et rémunérations annexes & & & & & &\tabularnewline
y compris IR et SFT & 6 588 & & 6 648 & & 6 660 &\tabularnewline
\bottomrule
\end{longtable}

\emph{Champ : France. Salariés en équivalent-temps plein (EQTP) des
collectivités territoriales (y compris bénéficiaires de contrats aidés,
hors assistantes maternelles).}\\
\emph{Les primes sont cumulées au supplément familial de traitement
(SFT) et à l'indemnité de résidence (IR). Le cumul est rapporté à la
rémunération brute totale.}\\
\href{../Docs/ip1486.xls}{Source INSEE}\\
\href{../Docs/Vue3_Remuneration_2017.xlsx}{Source DGCL}\\
\href{../Docs/Vue-Remunerations-2018.xlsx}{Source DGCL}\\
\href{../Docs/RA_2015.pdf}{Source RAEFP 2015}\\
\href{../Docs/RA_2016.pdf}{Source RAEFP 2016}\\
\href{../Docs/RA_2017.pdf}{Source RAEFP 2017}\\
\href{../Docs/RA_2018.pdf}{Source RAEFP 2018}

\hypertarget{cout-charge}{%
\subsection{3.6 Coût chargé}\label{cout-charge}}

\textbf{Les liens ci-après renvoient vers des tableaux présentant le
coût moyen chargé par agent}

\href{../Bases/Remunerations/cout.eqtp.csv}{Coût moyen chargé par grade}

\href{../Bases/Remunerations/cout.eqtp.emploi.csv}{Coût moyen chargé par
emploi}

\hypertarget{remunerations-nettes-evolutions-sur-la-periode-sous-revue}{%
\section{4. Rémunérations nettes : évolutions sur la periode sous
revue}\label{remunerations-nettes-evolutions-sur-la-periode-sous-revue}}

\textbf{Nombre d'exercices: 1 }

\textbf{Périmètre des données}\\
\textbf{Les données présentées dans cette section sont toutes relatives
à des rémunérations nettes en équivalent temps plein (EQTP)}\\
\textbf{Les élus, les vacataires et les assistantes maternelles ont été
retirés de la population étudiée}\\
\textbf{Seuls sont considérés les postes actifs et non annexes}

\emph{Nota :}\\
\emph{Rémunération annualisée en EQTP (Equivalent temps plein) : la
rémunération annuelle équivalente pour un temps plein en année pleine
est calculée pour chaque agent}\\
\emph{Chaque agent est rentre ensuite dans la somme avec la pondération
correspondant à son temps de travail annuel. }

\hypertarget{distribution-de-la-remuneration-nette-moyenne-sur-la-periode}{%
\subsection{4.1 Distribution de la rémunération nette moyenne sur la
periode}\label{distribution-de-la-remuneration-nette-moyenne-sur-la-periode}}

\includegraphics{altair_files/figure-latex/unnamed-chunk-115-1.png}

\includegraphics{altair_files/figure-latex/unnamed-chunk-116-1.png}

\href{../Bases/Remunerations/Analyse.variations.csv}{Lien vers la base de
données synthétique}\\
\href{../Bases/Remunerations/Analyse.variations.par.exercice.csv}{Lien vers
la base de données détaillée par année}

\hypertarget{evolutions-du-smpt-sur-la-periode-sous-revue}{%
\subsection{4.2 Evolutions du SMPT sur la periode sous
revue}\label{evolutions-du-smpt-sur-la-periode-sous-revue}}

\hypertarget{evolution-du-smpt-pour-lensemble-des-personnels-fonctionnaires-et-non-titulaires-hors-elus}{%
\subsubsection{4.2.1 Evolution du SMPT pour l'ensemble des personnels
fonctionnaires et non titulaires (hors
élus)}\label{evolution-du-smpt-pour-lensemble-des-personnels-fonctionnaires-et-non-titulaires-hors-elus}}

\textbf{Salaire net moyen par tête (SMPT net) en EQTP, hors élus}

~\emph{Tableau 4.2.1.1}

\begin{longtable}[]{@{}ccccc@{}}
\toprule
\begin{minipage}[b]{0.07\columnwidth}\centering
Annee\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\centering
smpt net (euros)\strut
\end{minipage} & \begin{minipage}[b]{0.15\columnwidth}\centering
Variation (\%)\strut
\end{minipage} & \begin{minipage}[b]{0.32\columnwidth}\centering
smpt net temps complet (euros)\strut
\end{minipage} & \begin{minipage}[b]{0.15\columnwidth}\centering
Variation (\%)\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.07\columnwidth}\centering
2015\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\centering
21 112\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\centering
0\strut
\end{minipage} & \begin{minipage}[t]{0.32\columnwidth}\centering
21 809\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\centering
0\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{Distribution et variation sur la periode du salaire moyen net
par tête (SMPT net) en EQTP}\\
\textbf{pour les salariés à temps complet}

~\emph{Tableau 4.2.1.2}

\begin{longtable}[]{@{}rrrrrrrrr@{}}
\toprule
Statistique & 2015 & Effectif & 2015 TC & Effectif & 2015 & Effectif &
2015 TC & Effectif\tabularnewline
\midrule
\endhead
Minimum & 6 370 & & 7 322 & & 6 370 & & 7 322 &\tabularnewline
1er quartile & 17 658 & & 17 730 & & 17 658 & & 17 730 &\tabularnewline
Médiane & 18 630 & & 18 719 & & 18 630 & & 18 719 &\tabularnewline
Moyenne & 21 112 & 3730 & 21 809 & 2268 & 21 112 & 3730 & 21 809 &
2268\tabularnewline
3ème quartile & 20 971 & & 21 377 & & 20 971 & & 21 377 &\tabularnewline
Maximum & 137 459 & & 137 459 & & 137 459 & & 137 459 &\tabularnewline
\bottomrule
\end{longtable}

\emph{Nota :} La population retenue est constituée des agents qui ne
font pas partie des 2 centiles extrêmaux

Les élus, vacataires et assistantes maternelles sont retirés du
périmètre.\\
TC : personnels à temps complet sur toute l'annee\\
Seuls sont pris en compte les agents ayant connu au moins un mois actif
et ayant eu, sur l'annee, des rémunérations non annexes.\\
\href{../Docs/méthodologie.pdf}{Compléments méthodologiques}

\textbf{Comparaisons source INSEE/DGCL}

\textbf{Salaires nets annuels moyens en EQTP (hors assistantes
maternelles) dans la FPT}

~\emph{Tableau 4.2.1.3}

\begin{longtable}[]{@{}lrrrrrr@{}}
\toprule
net (euros) & 2011 & 2012 & 2013 & 2014 & 2016 & 2017\tabularnewline
\midrule
\endhead
Ensemble & 21 876 & 22 176 & 22 224 & 22 524 & 22 824 & 23
328\tabularnewline
Titulaires & 22 632 & 22 920 & 22 920 & 23 424 & 23 820 & 24
312\tabularnewline
Autres salariés* & 18 864 & NA & NA & 18 732 & 20 207 & 20
532\tabularnewline
\bottomrule
\end{longtable}

*Contractuels à partir de 2017

\emph{Champ : France. Salariés en équivalent-temps plein (EQTP) des
collectivités territoriales (y compris bénéficiaires de contrats aidés,
hors assistantes maternelles).}

\textbf{Distribution des salaires nets annuels en EQTP dans la fonction
publique territoriale (2011-2016)}

~\emph{Tableau 4.2.1.4}

\begin{longtable}[]{@{}llllll@{}}
\toprule
Décile ~euros & 2011 FPT & 2013 FPT & 2014 FPT & 2016 FPT & 2017
FPT\tabularnewline
\midrule
\endhead
D1 & 15 288 & 15 600 & 15 768 & 15 912 & 16 272\tabularnewline
D2 & 16 512 & 16 860 & 17 124 & 17 340 & 17 688\tabularnewline
D3 & 17 508 & 17 844 & 18 156 & 18 432 & 18 828\tabularnewline
D4 & 18 480 & 18 816 & 19 164 & 19 476 & 19 908\tabularnewline
D5 (médiane) & 19 632 & 19 908 & 20 256 & 20 616 & 21 096\tabularnewline
D6 & 21 012 & 21 300 & 21 648 & 22 020 & 22 548\tabularnewline
D7 & 22 860 & 23 160 & 23 496 & 23 868 & 24 444\tabularnewline
D8 & 25 596 & 25 956 & 26 292 & 26 700 & 27 336\tabularnewline
D9 & 30 876 & 31 272 & 31 596 & 31 968 & 32 652\tabularnewline
Moyenne & 21 876 & 22 212 & 22 524 & 22 824 & 23 328\tabularnewline
\bottomrule
\end{longtable}

\textbf{Distribution des salaires nets annuels en EQTP dans la fonction
publique d'Etat (2011-2016)}

~\emph{Tableau 4.2.1.5}

\begin{longtable}[]{@{}llll@{}}
\toprule
Décile ~euros & 2011 & 2013 & 2016\tabularnewline
\midrule
\endhead
D1 & 17 496 & 18 012 & 17 928\tabularnewline
D2 & 20 916 & 21 348 & 21 588\tabularnewline
D3 & 23 052 & 23 376 & 23 844\tabularnewline
D4 & 24 912 & 25 248 & 25 764\tabularnewline
D5 (médiane) & 26 832 & 27 120 & 27 720\tabularnewline
D6 & 28 944 & 29 220 & 29 760\tabularnewline
D7 & 31 632 & 31 968 & 32 604\tabularnewline
D8 & 35 592 & 35 964 & 36 588\tabularnewline
D9 & 42 456 & 42 780 & 43 332\tabularnewline
Moyenne & 29 208 & 29 628 & 30 060\tabularnewline
\bottomrule
\end{longtable}

\textbf{Distribution des salaires nets annuels en EQTP dans la fonction
publique hospitalière (hôpitaux) (2011-2016)}

~\emph{Tableau 4.2.1.6}

\begin{longtable}[]{@{}lllll@{}}
\toprule
Décile ~euros & 2011 & 2013 & 2016 & 2017\tabularnewline
\midrule
\endhead
D1 & 16 584 & 17 016 & 17 460 & 17 688\tabularnewline
D2 & 18 168 & 18 492 & 18 852 & 19 104\tabularnewline
D3 & 19 620 & 19 872 & 20 160 & 20 460\tabularnewline
D4 & 21 048 & 21 192 & 21 456 & 21 816\tabularnewline
D5 (médiane) & 22 596 & 22 656 & 22 848 & 23 220\tabularnewline
D6 & 24 504 & 24 516 & 24 540 & 24 888\tabularnewline
D7 & 27 216 & 27 252 & 27 108 & 27 408\tabularnewline
D8 & 30 996 & 31 176 & 31 092 & 31 404\tabularnewline
D9 & 37 812 & 38 100 & 38 064 & 38 388\tabularnewline
Moyenne & 26 496 & 26 916 & 27 096 & 27 456\tabularnewline
\bottomrule
\end{longtable}

\href{../Docs/ip1486.xls}{Source INSEE, onglets Figure3, F1web et F3web -
2011}\\
\href{../Docs/vue3_remunerations.xls}{Source INSEE, onglets F V3.1-2, F
V3.1-5 - 2013}\\
\href{../Docs/Vue-Remunerations-2018.xlsx}{Source INSEE, onglet v3-2, V3-5
2016}

\hypertarget{evolution-du-smpt-des-fonctionnaires}{%
\subsubsection{4.2.2 Evolution du SMPT des
fonctionnaires}\label{evolution-du-smpt-des-fonctionnaires}}

\hypertarget{toutes-categories-statutaires}{%
\subparagraph{4.2.2.1 Toutes categories
statutaires}\label{toutes-categories-statutaires}}

\textbf{Salaire net moyen par tête (SMPT net) en EQTP}

~\emph{Tableau 4.2.2.1.1}

\begin{longtable}[]{@{}ccccc@{}}
\toprule
\begin{minipage}[b]{0.07\columnwidth}\centering
Annee\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\centering
smpt net (euros)\strut
\end{minipage} & \begin{minipage}[b]{0.15\columnwidth}\centering
Variation (\%)\strut
\end{minipage} & \begin{minipage}[b]{0.32\columnwidth}\centering
smpt net temps complet (euros)\strut
\end{minipage} & \begin{minipage}[b]{0.15\columnwidth}\centering
Variation (\%)\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.07\columnwidth}\centering
2015\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\centering
21 208\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\centering
0\strut
\end{minipage} & \begin{minipage}[t]{0.32\columnwidth}\centering
21 349\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\centering
0\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{par-categorie-statutaire}{%
\subparagraph{4.2.2.2 Par categorie
statutaire}\label{par-categorie-statutaire}}

\textbf{Categorie A}

~\emph{Tableau 4.2.2.2.1}

\begin{longtable}[]{@{}ccccc@{}}
\toprule
\begin{minipage}[b]{0.07\columnwidth}\centering
Annee\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\centering
smpt net (euros)\strut
\end{minipage} & \begin{minipage}[b]{0.15\columnwidth}\centering
Variation (\%)\strut
\end{minipage} & \begin{minipage}[b]{0.32\columnwidth}\centering
smpt net temps complet (euros)\strut
\end{minipage} & \begin{minipage}[b]{0.15\columnwidth}\centering
Variation (\%)\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.07\columnwidth}\centering
2015\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\centering
38 027\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\centering
0\strut
\end{minipage} & \begin{minipage}[t]{0.32\columnwidth}\centering
38 877\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\centering
0\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emph{Comparaisons nationales}\\
\emph{FPT categorie A}

\begin{longtable}[]{@{}lllll@{}}
\toprule
Décile ~euros & 2011 & 2013 & 2014 & 2016\tabularnewline
\midrule
\endhead
D1 & 26 040 & 26 340 & 26 460 & 26 724\tabularnewline
D2 & 28 992 & & &\tabularnewline
D3 & 31 272 & & &\tabularnewline
D4 & 33 468 & & &\tabularnewline
D5 (médiane) & 35 820 & 36 312 & 36 580 & 37 020\tabularnewline
D6 & 38 664 & & &\tabularnewline
D7 & 42 276 & & &\tabularnewline
D8 & 47 124 & & &\tabularnewline
D9 & 54 840 & 55 032 & 55 440 & 55 284\tabularnewline
Moyenne & 38 700 & 39 120 & 39 360 & 39 564\tabularnewline
\bottomrule
\end{longtable}

\textbf{Categorie B}

~\emph{Tableau 4.2.2.2.2}

\begin{longtable}[]{@{}ccccc@{}}
\toprule
\begin{minipage}[b]{0.07\columnwidth}\centering
Annee\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\centering
smpt net (euros)\strut
\end{minipage} & \begin{minipage}[b]{0.15\columnwidth}\centering
Variation (\%)\strut
\end{minipage} & \begin{minipage}[b]{0.32\columnwidth}\centering
smpt net temps complet (euros)\strut
\end{minipage} & \begin{minipage}[b]{0.15\columnwidth}\centering
Variation (\%)\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.07\columnwidth}\centering
2015\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\centering
26 410\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\centering
0\strut
\end{minipage} & \begin{minipage}[t]{0.32\columnwidth}\centering
26 108\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\centering
0\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emph{Comparaisons nationales}\\
\emph{FPT categorie B}

\begin{longtable}[]{@{}lllll@{}}
\toprule
Décile ~euros & 2011 & 2013 & 2014 & 2016\tabularnewline
\midrule
\endhead
D1 & 20 580 & 20 964 & 21 108 & 21 372\tabularnewline
D2 & 22 272 & & &\tabularnewline
D3 & 23 652 & & &\tabularnewline
D4 & 24 960 & & &\tabularnewline
D5 (médiane) & 26 244 & 26 820 & 27 000 & 27 216\tabularnewline
D6 & 27 636 & & &\tabularnewline
D7 & 29 160 & & &\tabularnewline
D8 & 30 984 & & &\tabularnewline
D9 & 33 804 & 34 224 & 34 344 & 34 560\tabularnewline
Moyenne & 26 940 & 27 408 & 27 588 & 27 828\tabularnewline
\bottomrule
\end{longtable}

\textbf{Categorie C}

~\emph{Tableau 4.2.2.2.3}

\begin{longtable}[]{@{}ccccc@{}}
\toprule
\begin{minipage}[b]{0.07\columnwidth}\centering
Annee\strut
\end{minipage} & \begin{minipage}[b]{0.18\columnwidth}\centering
smpt net (euros)\strut
\end{minipage} & \begin{minipage}[b]{0.15\columnwidth}\centering
Variation (\%)\strut
\end{minipage} & \begin{minipage}[b]{0.32\columnwidth}\centering
smpt net temps complet (euros)\strut
\end{minipage} & \begin{minipage}[b]{0.15\columnwidth}\centering
Variation (\%)\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.07\columnwidth}\centering
2015\strut
\end{minipage} & \begin{minipage}[t]{0.18\columnwidth}\centering
18 819\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\centering
0\strut
\end{minipage} & \begin{minipage}[t]{0.32\columnwidth}\centering
18 697\strut
\end{minipage} & \begin{minipage}[t]{0.15\columnwidth}\centering
0\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\emph{Comparaisons nationales}\\
\emph{FPT categorie C}

\begin{longtable}[]{@{}lllll@{}}
\toprule
Décile ~euros & 2011 & 2013 & 2014 & 2016\tabularnewline
\midrule
\endhead
D1 & 15 972 & 16 296 & 16 632 & 16 920\tabularnewline
D2 & 16 896 & & &\tabularnewline
D3 & 17 652 & & &\tabularnewline
D4 & 18 360 & & &\tabularnewline
D5 (médiane) & 19 164 & 19 464 & 19 884 & 20 256\tabularnewline
D6 & 20 100 & & &\tabularnewline
D7 & 21 216 & & &\tabularnewline
D8 & 22 680 & & &\tabularnewline
D9 & 24 996 & 25 176 & 25 608 & 26 028\tabularnewline
Moyenne & 20 016 & 20 268 & 20 676 & 21 024\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{distribution-et-variation-sur-la-periode-du-smpt-net-en-eqtp}{%
\subsubsection{4.2.3 Distribution et variation sur la periode du SMPT
net en
EQTP}\label{distribution-et-variation-sur-la-periode-du-smpt-net-en-eqtp}}

\hypertarget{pour-lensemble-des-categories-statutaires}{%
\paragraph{4.2.3.1 Pour l'ensemble des categories
statutaires}\label{pour-lensemble-des-categories-statutaires}}

\textbf{Fonctionnaires}\\
\hspace*{0.333em}\emph{Tableau 4.2.3.1.1}

\begin{longtable}[]{@{}rrrrrrrrr@{}}
\toprule
Statistique & 2015 & Effectif & 2015 TC & Effectif & 2015 & Effectif &
2015 TC & Effectif\tabularnewline
\midrule
\endhead
Minimum & 6 817 & & 7 322 & & 6 817 & & 7 322 &\tabularnewline
1er quartile & 17 752 & & 17 751 & & 17 752 & & 17 751 &\tabularnewline
Médiane & 18 781 & & 18 712 & & 18 781 & & 18 712 &\tabularnewline
Moyenne & 21 208 & 3069 & 21 349 & 2125 & 21 208 & 3069 & 21 349 &
2125\tabularnewline
3ème quartile & 21 067 & & 21 091 & & 21 067 & & 21 091 &\tabularnewline
Maximum & 83 869 & & 83 869 & & 83 869 & & 83 869 &\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{par-categorie-statutaire-1}{%
\paragraph{4.2.3.2 Par categorie
statutaire}\label{par-categorie-statutaire-1}}

\textbf{Categorie A}\\
\hspace*{0.333em}\emph{Tableau 4.2.3.2.1}

\begin{longtable}[]{@{}rrrrrrrrr@{}}
\toprule
Statistique & 2015 & Effectif & 2015 TC & Effectif & 2015 & Effectif &
2015 TC & Effectif\tabularnewline
\midrule
\endhead
Minimum & 14 557 & & 14 557 & & 14 557 & & 14 557 &\tabularnewline
1er quartile & 30 214 & & 30 529 & & 30 214 & & 30 529 &\tabularnewline
Médiane & 36 058 & & 36 996 & & 36 058 & & 36 996 &\tabularnewline
Moyenne & 38 027 & 330 & 38 877 & 233 & 38 027 & 330 & 38 877 &
233\tabularnewline
3ème quartile & 43 830 & & 45 258 & & 43 830 & & 45 258 &\tabularnewline
Maximum & 83 869 & & 83 869 & & 83 869 & & 83 869 &\tabularnewline
\bottomrule
\end{longtable}

\textbf{Categorie B}\\
\hspace*{0.333em}\emph{Tableau 4.2.3.2.2}

\begin{longtable}[]{@{}rrrrrrrrr@{}}
\toprule
Statistique & 2015 & Effectif & 2015 TC & Effectif & 2015 & Effectif &
2015 TC & Effectif\tabularnewline
\midrule
\endhead
Minimum & 16 717 & & 16 717 & & 16 717 & & 16 717 &\tabularnewline
1er quartile & 23 581 & & 23 434 & & 23 581 & & 23 434 &\tabularnewline
Médiane & 25 518 & & 25 441 & & 25 518 & & 25 441 &\tabularnewline
Moyenne & 26 410 & 162 & 26 108 & 123 & 26 410 & 162 & 26 108 &
123\tabularnewline
3ème quartile & 28 252 & & 28 209 & & 28 252 & & 28 209 &\tabularnewline
Maximum & 63 675 & & 55 445 & & 63 675 & & 55 445 &\tabularnewline
\bottomrule
\end{longtable}

\textbf{Categorie C}\\
\hspace*{0.333em}\emph{Tableau 4.2.3.2.3}

\begin{longtable}[]{@{}rrrrrrrrr@{}}
\toprule
Statistique & 2015 & Effectif & 2015 TC & Effectif & 2015 & Effectif &
2015 TC & Effectif\tabularnewline
\midrule
\endhead
Minimum & 6 817 & & 7 322 & & 6 817 & & 7 322 &\tabularnewline
1er quartile & 17 684 & & 17 679 & & 17 684 & & 17 679 &\tabularnewline
Médiane & 18 425 & & 18 362 & & 18 425 & & 18 362 &\tabularnewline
Moyenne & 18 819 & 2576 & 18 697 & 1768 & 18 819 & 2576 & 18 697 &
1768\tabularnewline
3ème quartile & 19 740 & & 19 657 & & 19 740 & & 19 657 &\tabularnewline
Maximum & 45 114 & & 45 114 & & 45 114 & & 45 114 &\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Remunerations/Analyse.variations.par.exercice.csv}{Lien vers
la base de données}

\hypertarget{remuneration-moyenne-des-personnes-en-place-rmpp-et-effet-de-noria}{%
\subsection{4.3 Rémunération moyenne des personnes en place (RMPP) et
effet de
noria}\label{remuneration-moyenne-des-personnes-en-place-rmpp-et-effet-de-noria}}

\hypertarget{rmpp-de-lensemble-des-personnels-titulaires-et-non-titulaires}{%
\subsubsection{4.3.1 RMPP de l'ensemble des personnels titulaires et
non-titulaires}\label{rmpp-de-lensemble-des-personnels-titulaires-et-non-titulaires}}

\hypertarget{application-de-filtres-sur-les-donnees}{%
\subsubsection{Application de filtres sur les
données}\label{application-de-filtres-sur-les-donnees}}

\textbf{Afin d'apprécier la sensibilité des résultats à la qualité ou
aux valeurs extrêmes des données, le filtrage suivant est à présent
appliqué.}\\
\textbf{Sont retirés les valeurs manquantes des variations, les centiles
extrêmaux, les rémunérations nettes négatives (rappels) ou proche de
zéro.}

\textbf{Un statut explicite doit être renseigné en fin de periode. Des
rémunérations doivent être versées à la fois en début et en fin de
periode de paiement de l'agent, supérieures à 0,5 . Le nombre de jours
d'exercice doit être supérieur à 4 .}

\textbf{Ces filtres sont référencés ci-après par les termes ``filtres
sur RMPP''.}

\emph{Cet histogramme décrit l'évolution de la rémunération moyenne des
personnes en place (RMPP), définies comme présentes deux annees entières
consécutives avec la même quotité}\\
\emph{L'évolution de la RMPP permet d'étudier le glissement
vieillesse-technicité ``positif'', à effectifs constants sur deux
années}

\textbf{Variation individuelle de rémunération nette en EQTP pour les
personnels présents sur toute la periode}

~\emph{Tableau 4.3.1.1}

\hypertarget{rmpp-des-titulaires-et-stagiaires}{%
\subsubsection{4.3.2 RMPP des titulaires et
stagiaires}\label{rmpp-des-titulaires-et-stagiaires}}

\textbf{Variation individuelle de rémunération nette en EQTP pour les
personnels présents sur toute la periode}

~\emph{Tableau 4.3.2.1}

\textbf{Nota}

\emph{Personnes en place :} en fonction au moins deux années
consécutives avec la même quotité sur la periode 2015 à 2015

\emph{Variation sur la periode d'activité :} entre l'arrivée et le
départ de la personne\\
\emph{Variation normalisée :} conforme à la définition INSEE (présente
en début et en fin de période avec la même quotité)

\textbf{Commentaire}

Les différences éventuelles constatées entre l'évolution de la RMPP au
tableau -2 sont dues soit à l'effet de noria soit à l'effet périmètre.

\hypertarget{les-filtres-rmpp-appliques-au-4.3.1-et-4.3.2-ne-sont-plus-appliques.-il-peut-en-resulter-des-variations-significativement-differentes-de-celles-calculees-precedemment.}{%
\subparagraph{Les filtres RMPP appliqués au 4.3.1 et 4.3.2 ne sont plus
appliqués. Il peut en résulter des variations significativement
différentes de celles calculees
précédemment.}\label{les-filtres-rmpp-appliques-au-4.3.1-et-4.3.2-ne-sont-plus-appliques.-il-peut-en-resulter-des-variations-significativement-differentes-de-celles-calculees-precedemment.}}

\hypertarget{effet-de-noria-et-de-variation-deffectifs-sur-remunerations-moyennes}{%
\subsubsection{4.3.3 Effet de noria et de variation d'effectifs sur
rémunérations
moyennes}\label{effet-de-noria-et-de-variation-deffectifs-sur-remunerations-moyennes}}

\emph{Les calculs de RMPP sur la première année de la periode sous revue
sont estimatifs et ne devraient pas être pris en compte pour
publication.}

\textbf{Effet de noria et de variations d'effectifs sur rémunérations
nettes moyennes EQTP}

~\emph{Tableau 4.3.3.1}

L'effet de noria ne peut être calcule que sur au moins deux exercices
consécutifs

\textbf{Effet de noria et de variations d'effectifs sur rémunérations
brutes moyennes EQTP}

~\emph{Tableau 4.3.3.2}

L'effet de noria ne peut être calcule que sur au moins deux exercices
consécutifs

\emph{Note :}\\
\emph{Effet de noria} : \emph{variation des rémunérations liées au
remplacement de salariés sortants par un même nombre d'entrants.}\\
\emph{Effet des variations d'effectifs (ou de périmètre)} :
\emph{variation des rémunérations liées à la différence entre nombre de
sortants et d'entrants.}\\
\emph{Les effets de vacances d'emploi, s'ils existent, sont intégrés
dans le calcul de l'effet de noria}\\
\emph{Voir les exemples traités en bas de page du lien technique
suivant}\\
\href{../Docs/Notices/noria.html}{Spécifications techniques des tables RMPP
et effet de noria}\\
\href{../Docs/Notices/GVT\%20et\%20noria.pdf}{Voir complément
méthodologique DGFIP}

\hypertarget{effet-de-noria-et-de-variation-deffectifs-sur-remunerations-moyennes-des-fonctionnaires}{%
\subsubsection{4.3.4 Effet de noria et de variation d'effectifs sur
rémunérations moyennes des
fonctionnaires}\label{effet-de-noria-et-de-variation-deffectifs-sur-remunerations-moyennes-des-fonctionnaires}}

\textbf{Effet de noria et de variations d'effectifs sur rémunérations
nettes moyennes EQTP des fonctionnaires}

~\emph{Tableau 4.3.4.1}

L'effet de noria ne peut être calcule que sur au moins deux exercices
consécutifs

\textbf{Effet de noria et de variations d'effectifs sur rémunérations
brutes moyennes EQTP des fonctionnaires}

~\emph{Tableau 4.3.4.2}

L'effet de noria ne peut être calcule que sur au moins deux exercices
consécutifs

\hypertarget{effet-de-noria-et-de-variation-deffectifs-sur-remunerations-moyennes-par-categorie-statutaire}{%
\subsubsection{4.3.5 Effet de noria et de variation d'effectifs sur
rémunérations moyennes par categorie
statutaire}\label{effet-de-noria-et-de-variation-deffectifs-sur-remunerations-moyennes-par-categorie-statutaire}}

\textbf{Effet de noria et de variations d'effectifs sur rémunérations
nettes moyennes EQTP des fonctionnaires de categorie A}

~\emph{Tableau 4.3.5.1}

L'effet de noria ne peut être calcule que sur au moins deux exercices
consécutifs

\textbf{Effet de noria et de variations d'effectifs sur rémunérations
brutes moyennes EQTP des fonctionnaires de categorie A}

~\emph{Tableau 4.3.5.2}

L'effet de noria ne peut être calcule que sur au moins deux exercices
consécutifs

\textbf{Effet de noria et de variations d'effectifs sur rémunérations
nettes moyennes EQTP des fonctionnaires de categorie B}

~\emph{Tableau 4.3.5.3}

L'effet de noria ne peut être calcule que sur au moins deux exercices
consécutifs

\textbf{Effet de noria et de variations d'effectifs sur rémunérations
brutes moyennes EQTP des fonctionnaires de categorie B}

~\emph{Tableau 4.3.5.4}

L'effet de noria ne peut être calcule que sur au moins deux exercices
consécutifs

\textbf{Effet de noria et de variations d'effectifs sur rémunérations
nettes moyennes EQTP des fonctionnaires de categorie C}

~\emph{Tableau 4.3.5.5}

L'effet de noria ne peut être calcule que sur au moins deux exercices
consécutifs

\textbf{Effet de noria et de variations d'effectifs sur rémunérations
brutes moyennes EQTP des fonctionnaires de categorie C}

~\emph{Tableau 4.3.5.6}

L'effet de noria ne peut être calcule que sur au moins deux exercices
consécutifs

\hypertarget{remunerations-nettes-par-grade-emploi-et-service}{%
\subsection{4.4 Rémunérations nettes par grade, emploi et
service}\label{remunerations-nettes-par-grade-emploi-et-service}}

\href{../Bases/Remunerations/net.grades.csv}{Rémunérations nettes par
grade}

\href{../Bases/Remunerations/net.emplois.csv}{Rémunérations nettes par
emploi}

\emph{Note : les moyennes des tableaux sont pondérées en EQTP. Les
rémunérations nettes sont calculees en retranchant le supplément
familial de traitement.}

\hypertarget{comparaisons-avec-la-situation-nationale-des-remunerations}{%
\subsection{4.5 Comparaisons avec la situation nationale des
rémunérations}\label{comparaisons-avec-la-situation-nationale-des-remunerations}}

\textbf{Évolution en euros courants du SMPT et de la RMPP dans la FPT
(en \% et euros courants)}

~\emph{Tableau 4.5.1}

\begin{longtable}[]{@{}crrrrrrrrr@{}}
\toprule
Annee & 2009 & 2010 & 2011 & 2012 & 2013 & 2014 & 2015 & 2016 &
2017\tabularnewline
\midrule
\endhead
SMPT brut & 2,5 & 1,3 & 1,5 & 1,7 & 1,1 & 1,7 & 1,2 & 0,9 &
2,4\tabularnewline
SMPT net & 3,0 & 1,4 & 1,3 & 1,4 & 0,8 & 1,3 & 0,8 & 0,6 &
2,1\tabularnewline
RMPP brute & 3,3 & 2,5 & 2,5 & 2,7 & 1,9 & 3,0 & 2,1 & 1,7 &
3,2\tabularnewline
RMPP nette & 3,3 & 2,5 & 2,3 & 2,4 & 1,6 & 2,7 & 1,7 & 1,3 &
2,8\tabularnewline
\bottomrule
\end{longtable}

\emph{Source : fichier général de l'État (FGE), DADS, SIASP, Insee,
Drees. Traitement Insee, Drees, DGCL}\\
Hors assistants maternels et familiaux, y compris bénéficiaires de
contrats aidés.\\
Lecture : en 2014, le SMPT brut en EQTP a augmenté de 1,7 \% SMPT :
Salaire moyen par tête en EQTP.\\
RMPP : Agents présents 24 mois consécutifs chez le même employeur avec
la même quotité de travail.\\
Lecture : en 2014, la rémunération nette en EQTP des agents présents
deux annees consécutives en 2012 et 2013 avec la même quotité a augmenté
de 2,7 \%

\textbf{Salaires nets annuels et évolution moyenne type de collectivité
en euros courants EQTP}

~\emph{Tableau 4.5.2}

\begin{longtable}[]{@{}crrrrrrr@{}}
\toprule
\begin{minipage}[b]{0.24\columnwidth}\centering
Organisme SMPT net\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
2011\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\raggedleft
2012\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
2013\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
2014\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\raggedleft
2015\strut
\end{minipage} & \begin{minipage}[b]{0.09\columnwidth}\raggedleft
2016\strut
\end{minipage} & \begin{minipage}[b]{0.07\columnwidth}\raggedleft
2017\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.24\columnwidth}\centering
Communes\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
20 784\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
21 120\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
21 096\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
21 444\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
21 552\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
21 632\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
22 116\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.24\columnwidth}\centering
CCAS et caisses des écoles\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
19 415\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
19 716\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
19 788\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
20 124\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
20 232\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
20 370\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
20 796\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.24\columnwidth}\centering
EPCI à fiscalité propre\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
22 882\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
23 088\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
23 184\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
23 412\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
23 424\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
23 754\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
24 288\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.24\columnwidth}\centering
Autres structures intercommunales\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
21 299\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
21 684\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
21 828\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
22 140\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
22 332\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
22 517\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
22 908\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.24\columnwidth}\centering
Départements\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
24 487\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
24 744\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
24 852\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
25 068\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
25 344\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
25 391\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
25 908\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.24\columnwidth}\centering
SDIS\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
29 811\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
29 940\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
30 180\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
30 480\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
30 912\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
31 147\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
31 740\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.24\columnwidth}\centering
Régions\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
22 432\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
22 836\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
23 004\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
23 484\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
23 808\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
24 284\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
24 936\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.24\columnwidth}\centering
Autres collectivités locales\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
24 680\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
24 696\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
24 828\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
25 032\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
25 368\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
25 456\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
25 848\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.24\columnwidth}\centering
Ensemble (moyenne)\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
21 873\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
22 176\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
22 212\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
22 524\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
22 692\strut
\end{minipage} & \begin{minipage}[t]{0.09\columnwidth}\raggedleft
22 819\strut
\end{minipage} & \begin{minipage}[t]{0.07\columnwidth}\raggedleft
23 328\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{RMPP nette (salariés présents deux années de suite avec la même
quotité) en EQTP}

\begin{longtable}[]{@{}crrrr@{}}
\toprule
Organisme RMPP net & 2014 & 2014-2015 (\%) & 2015-2016 (\%) & 2016-2017
(\%)\tabularnewline
\midrule
\endhead
Communes & 22 524 & 1,5 & 1,1 & 2,1\tabularnewline
CCAS et caisses des écoles & 21 420 & 1,6 & 1,1 & 2\tabularnewline
EPCI à fiscalité propre & 24 864 & 1,9 & 1,6 & 2\tabularnewline
Autres structures intercommunales & 23 988 & 2,1 & 1,7 &
1,6\tabularnewline
Départements & 25 932 & 1,9 & 1,3 & 1,8\tabularnewline
SDIS & 31 032 & 2,6 & 1,5 & 1,8\tabularnewline
Régions & 24 240 & 2,1 & 1,3 & 2,4\tabularnewline
Autres collectivités locales & 21 873 & 2,0 & 1,7 & 1,4\tabularnewline
Ensemble (moyenne) & 23 760 & 1,7 & 1,3 & 2,1\tabularnewline
\bottomrule
\end{longtable}

\emph{Champ : France. Salariés en équivalent-temps plein (EQTP) des
collectivités territoriales (y compris bénéficiaires de contrats aidés,
hors assistantes maternelles).}\\
Conversion en euros courants, calcul CRC. La métropole de Lyon est
classée avec les départements\\
\href{../Docs/RA_2016.pdf}{Source RAEFP 2016 données 2014}\\
\href{../Docs/RA_2017.pdf}{Source RAEFP 2017 données 2015}\\
\href{../Docs/RA_2018.pdf}{Source RAEFP 2018 données 2016}\\
\href{../Docs/RA_2019.pdf}{Source RAEFP 2019 données 2017}

\newpage

\hypertarget{tests-reglementaires}{%
\section{5. Tests réglementaires}\label{tests-reglementaires}}

\textbf{Dans cette partie, l'ensemble de la base de paie est étudié.}\\
Les agents non actifs ou dont le poste est annexe sont réintroduits dans
le périmètre.

\hypertarget{controle-des-nouvelles-bonifications-indiciaires-nbi}{%
\subsection{5.1 Contrôle des nouvelles bonifications indiciaires
(NBI)}\label{controle-des-nouvelles-bonifications-indiciaires-nbi}}

Il est fortement conseillé, pour ce test, de saisir les codes de NBI
dans l'onglet Codes de l'interface graphique ~
\href{../Docs/Notices/fiche_onglet_codes.odt}{\includegraphics{icones/Notice.png}}\\
A défaut, des lignes de paye de rappels de cotisations sur NBI peuvent
être agrégées, dans certains cas, aux rappels de rémunération brute.\\
Avertissement : les contrôles de liquidation et de proratisation
tiennent compte de rappels de paiement. D'importants écarts peuvent être
liés à des problèmes de qualité sur le renseignement des rappels.\\
En début et en fin de période, le fait que des rappels de paiement ne
soient pas disponibles peut également fausser les calculs.\\
Ces tests ne doivent donc donner lieu à instruction que si les écarts
constatés sont significatifs, en tenant compte des rappels et de la
manière dont ils sont comptabilisés,\\
qui peut différer de la modélisation adoptée (voir notices).

Pas de NBI en points non entiers.\\
Il existe 2 non titulaires percevant une NBI.Le champ Année de
rattachement du rappel n'est pas renseigné en base (défaut de qualité)
pour 90 ligne(s) de rappels.\\
L'année de rattachement du rappel est présumée être celle en cours.\\
Le champ Mois de rappel n'est pas renseigné en base (défaut de qualité)
pour 90 ligne(s) de rappel.Le mois de rattachement du rappel est présumé
être celui du mois en cours.

\href{../Bases/Reglementation/NBI.aux.non.titulaires.csv}{Lien vers la base
de données NBI aux non titulaires}

\href{../Docs/Notices/fiche_NBI_nt.odt}{\includegraphics{icones/Notice.png}}

~\emph{Tableau 5.1.1 : Contrôle de liquidation de la NBI}
\href{../Docs/Notices/fiche_NBI_liq.odt}{\includegraphics{icones/Notice.png}}

\begin{longtable}[]{@{}ccc@{}}
\toprule
Lignes de NBI concernées & Coûts correspondants & Rappels (montants
bruts)\tabularnewline
\midrule
\endhead
5 078 & 387 293,6 & 5 026,7\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.1.2 : Contrôle de liquidation de la NBI, hors rappels}
~
\href{../Docs/Notices/fiche_NBI_liq.odt}{\includegraphics{icones/Notice.png}}

\begin{longtable}[]{@{}cc@{}}
\toprule
Lignes de NBI concernées (hors rappels) & Coûts
correspondants\tabularnewline
\midrule
\endhead
5 078 & 387 293,6\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Fiabilite/lignes.nbi.anormales.csv}{Lien vers la base de
données des anomalies de NBI}\\
\href{../Bases/Fiabilite/lignes.nbi.anormales.hors.rappels.csv}{Lien vers
la base de données des anomalies de NBI hors rappels}

\textbf{Nota :}\\
\emph{Est considéré comme anomalie manifeste un total annuel de
rémunérations NBI correspondant à un point d'indice net mensuel
inférieur à la moyenne de l'annee moins 1 euro ou supérieur à cette
moyenne plus 1 euro.}\\
\emph{Les rappels ne sont pas pris en compte dans les montants versés.
Certains écarts peuvent être régularisés en les prenant en compte}

~\emph{Tableau 5.1.3 : Contrôle global de la liquidation des NBI} ~
\href{../Docs/Notices/fiche_NBI_glob.odt}{\includegraphics{icones/Notice.png}}

\href{../Bases/Fiabilite/cumuls.nbi.csv}{Lien vers la base de données des
cumuls annuels de NBI}

~\emph{Tableau 5.1.4 : Contrôle de proratisation/liquidation de la NBI}
~
\href{../Docs/Notices/fiche_NBI_prorat.odt}{\includegraphics{icones/Notice.png}}

Error in vecseq(f\_\_, len\textbf{, if (allow.cartesian
\textbar{}\textbar{} notjoin \textbar{}\textbar{} !anyDuplicated(f}, :
Join results in 90400 rows; more than 53260 = nrow(x)+nrow(i). Check for
duplicate key values in i each of which join to the same group in x over
and over again. If that's ok, try by=.EACHI to run j for each group to
avoid the large allocation. If you are sure you wish to proceed, rerun
with allow.cartesian=TRUE. Otherwise, please search for this error
message in the FAQ, Wiki, Stack Overflow and data.table issue tracker
for advice. La vérification de la proratisation de la NBI n'a pas pu
être réalisée.

\begin{longtable}[]{@{}cc@{}}
\toprule
Differences \textgreater{} 2 euro : nombre de lignes & Coût total des
différences\tabularnewline
\midrule
\endhead
10 310 & 0\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Fiabilite/lignes.nbi.anormales.mensuel.csv}{Lien vers les
bulletins anormaux du contrôle de proratisation/liquidation de la NBI}

~\emph{Tableau 5.1.5 : Contrôle d'attribution de NBI par categorie
statutaire} ~
\href{../Docs/Notices/fiche_plafonds_NBI.odt}{\includegraphics{icones/Notice.png}}

\begin{longtable}[]{@{}cc@{}}
\toprule
Nombre d'agents concernés & Coût total des dépassements\tabularnewline
\midrule
\endhead
2 & 6 111,8\tabularnewline
\bottomrule
\end{longtable}

\textbf{Nota :}\\
Coût annuel calcule pour la quotite de travail observée, limité aux
dépassements des maxima ci-après.\\
Dépassements de NBI :\\
- plus de 50 points pour la categorie A;\\
- plus de 30 points pour la categorie B;\\
- plus de 20 points pour la categorie C.\\
Directeurs généraux adjoints : plus de 80 points.\\
Directeurs généraux adjoints : plus de 120 points.

\href{../Bases/Reglementation/NBI.cat.irreg.csv}{Lien vers les NBI
dépassant les seuils par categorie statutaire}

\hypertarget{controle-sur-les-heures-supplementaires}{%
\subsection{5.11 Contrôle sur les heures
supplémentaires}\label{controle-sur-les-heures-supplementaires}}

\href{../Docs/Notices/fiche_IHTS.odt}{\includegraphics{icones/Notice.png}}

~\emph{Tableau 5.11.1 : Paiements au-delà des seuils de liquidation pour
l'exercice}

25 attributaires des IHTS sont des non-titulaires.\\
\textbf{Vérifier l'existence d'une délibération} le prévoyant
expressément.\\
Pas de dépassement détecté du maximum d'IHTS pouvant être liquidé au
titre du mois.

~
\href{../Docs/Notices/fiche_liquidation_IHTS.odt}{\includegraphics{icones/Notice.png}}

\href{../Bases/Reglementation/Base.IHTS.non.tit.csv}{Lien vers la base de
données des IHTS aux non-titulaires}

\href{../Bases/Reglementation/Taux.horaires.csv}{Lien vers la base de
données calcul des taux horaires individuels}

\emph{Le cumul des heures supplémentaires déclarées (colonne Heures.Sup.
des bases) est, par année, comparé au cumul des bases de liquidation
IHTS, pour l'année et en régularisation l'année suivante au titre du
même exercice}\\
\emph{Le volume d'heures supplémentaires déclarées et non liquidées sous
forme d'IHTS peut correspondre à d'autres régimes d'heures
supplémentaires (enseignants, élections) ou à des heures supplémentaires
non effectuées ou sous-déclarées}\\
\emph{Des différences importantes peuvent indiquer une mauvaise
fiabilité des déclarations d'heures supplémentaires et/ou des bases de
liquidation IHTS}

~\emph{Tableau 5.11.2 : Cumuls d'heures supplémentaires déclarées et des
IHTS payees, en nombre d'heures}

\begin{longtable}[]{@{}llllll@{}}
\toprule
Annee N & Cumul HS N & Cumul IHTS N & dont du mois & dont rappels N &
dont payes N+1\tabularnewline
\midrule
\endhead
2015 & 27 040,2 & 331,0 & 331,0 & &\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Reglementation/CumHS.csv}{Lien vers les données du
tableau}\\
\href{../Bases/Reglementation/lignes.IHTS.tot.csv}{Lien vers les cumuls
IHTS par matricule}\\
\href{../Bases/Reglementation/lignes.IHTS.csv}{Lien vers les lignes IHTS}

~\emph{Tableau 5.11.3 : Heures supplémentaires au-delà des seuils}

Les cumuls d'IHTS sont déterminés à partir des paiements de l'année,
rappels compris, et des rappels payés l'année suivante.

\begin{longtable}[]{@{}cc@{}}
\toprule
Nombre de lignes HS en excès & Nombre de lignes IHTS cat.
A\tabularnewline
\midrule
\endhead
12 & 42\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Reglementation/HS.sup.25.csv}{Lien vers la base de données
Heures supplémentaires en excès du seuil de 15h (FPH) ou de 25h/mois
(FPT)}

\href{../Bases/Reglementation/ihts.cat.A.csv}{Lien vers la base de données
IHTS versées à des fonctionnaires de cat. A}

\textbf{Nota :}\\
HS en excès : au-delà de 25 heures par mois dans la FPT et 15 heures par
mois dans la FPH, sauf pour certains emplois (18,3 heures par mois)\\
IHTS cat.A : attribuées à des fonctionnaires ou non-titulaires de
categorie A ou assimilés.\\
Dans les tableaux en lien les grades, emplois et service sont ceux
connus en fin d'annee.

\hypertarget{controle-des-indemnites-pour-astreintes}{%
\subsection{5.12 Contrôle des indemnités pour
astreintes}\label{controle-des-indemnites-pour-astreintes}}

\href{../Docs/Notices/fiche_astreintes.odt}{\includegraphics{icones/Notice.png}}

~\emph{Tableau 5.12.1 : Cumuls irréguliers NBI et astreintes
(responsabilité supérieure)}

\begin{longtable}[]{@{}ll@{}}
\toprule
Annee & Montant astreintes irrégulières (euros)\tabularnewline
\midrule
\endhead
Total &\tabularnewline
\bottomrule
\end{longtable}

\textbf{Nota}\\
Vérifier l'adéquation des libellés de paye d'astreinte dans le tableau
en lien ci-après.\\
Définition des fonctions de responsabilité supérieure : décrets du 27
décembre 2001 et du 28 décembre 200

\href{../Bases/Reglementation/libelles.astreintes.csv}{Lien vers les
libellés et codes astreintes}

Des astreintes sont payees à 7 personnels bénéficiaires d'IHTS.

~\emph{Tableau 5.12.2 : Cumuls potentiellement irréguliers IHTS et
astreintes}

\begin{longtable}[]{@{}lll@{}}
\toprule
\begin{minipage}[b]{0.07\columnwidth}\raggedright
Annee\strut
\end{minipage} & \begin{minipage}[b]{0.55\columnwidth}\raggedright
Montant astreintes potentiellement irrégulières (euros)\strut
\end{minipage} & \begin{minipage}[b]{0.29\columnwidth}\raggedright
Montant IHTS correspondantes\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.07\columnwidth}\raggedright
2015\strut
\end{minipage} & \begin{minipage}[t]{0.55\columnwidth}\raggedright
10 036,4\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\raggedright
97 368,4\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.07\columnwidth}\raggedright
Total\strut
\end{minipage} & \begin{minipage}[t]{0.55\columnwidth}\raggedright
10 036,4\strut
\end{minipage} & \begin{minipage}[t]{0.29\columnwidth}\raggedright
97 368,4\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{Nota}:\\
Les cumuls peuvent être réguliers s'il y a eu des interventions non
compensées en periode d'astreinte.

\href{../Bases/Reglementation/Controle_astreintes_HS_irreg.csv}{Lien vers
la base des cumuls astreintes/IHTS}\\
\href{../Bases/Reglementation/Cum_astreintes_HS_irreg.csv}{Lien vers les
cumuls annuels}

\hypertarget{controle-sur-les-indemnites-iat-et-ifts}{%
\subsection{5.6 Contrôle sur les indemnités IAT et
IFTS}\label{controle-sur-les-indemnites-iat-et-ifts}}

\href{../Docs/Notices/fiche_IAT_IFTS.odt}{\includegraphics{icones/Notice.png}}

6 attributaires de IFTS ne satisfont pas au critère de la borne
indiciaire (INM 350). 3 attributaires IFTS sont des non-titulaires. Tous
les attributaires de IFTS sont identifiés en categorie A B . 44
attributaires IAT sont des non-titulaires. 1 attributaires de IAT ne
sont pas identifiés en categorie B C .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes IAT & Agents cumulant IAT et IFTS\tabularnewline
\midrule
\endhead
452.50 452.50 R & 4\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{controle-sur-les-iat-pour-categories-b-c-et-non-titulaires}{%
\subsubsection{Contrôle sur les IAT pour categories B C et
non-titulaires}\label{controle-sur-les-iat-pour-categories-b-c-et-non-titulaires}}

\href{../Bases/Reglementation/IAT.non.tit.csv}{Lien vers la base de données
IAT aux non-titulaires}\\
\href{../Bases/Reglementation/IAT.non.catBC.csv}{Lien vers la base de
données IAT non cat B-C}

\hypertarget{controle-sur-les-ifts-pour-categories-b-et-non-titulaires}{%
\subsubsection{Contrôle sur les IFTS pour categories B et
non-titulaires}\label{controle-sur-les-ifts-pour-categories-b-et-non-titulaires}}

\href{../Bases/Reglementation/IFTS.indice.anormal.csv}{Lien vers la base de
données IFTS à des catég. B INM inférieur à 350}\\
\href{../Bases/Reglementation/IFTS.non.tit.csv}{Lien vers la base de
données IFTS aux non-titulaires}

~\emph{Tableau 5.6.1 : Cumul IAT/IFTS}

\begin{longtable}[]{@{}lrll@{}}
\toprule
Matricule & Annee & Grade & Régime\tabularnewline
\midrule
\endhead
1092 & 2015 & RÉDACTEUR & IFTS 8 mois-IAT 3 mois-Cumul 1
mois\tabularnewline
1246 & 2015 & RÉDACTEUR & IFTS 8 mois-IAT 3 mois-Cumul 1
mois\tabularnewline
5144 & 2015 & RÉDACTEUR & IFTS 6 mois-IAT 5 mois-Cumul 1
mois\tabularnewline
879 & 2015 & RÉDACTEUR & IFTS 9 mois-IAT 2 mois-Cumul 1
mois\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Reglementation/personnels.iat.ifts.csv}{Lien vers la base de
données cumuls IAT/IFTS}

\hypertarget{controle-sur-le-cumul-logement-par-nas-et-ifts}{%
\subsubsection{Contrôle sur le cumul logement par NAS et
IFTS}\label{controle-sur-le-cumul-logement-par-nas-et-ifts}}

~\emph{Tableau 5.6.2 : Cumul logement par NAS/IFTS}

Pas de cumuls prime-NAS.\\
La base des logements par NAS n'est pas détectée.\\
Le test de compatibilité de la prime avec les concessions de logements
ne sera pas réalisé.

\hypertarget{controle-de-la-prime-de-fonctions-et-de-resultats-pfr}{%
\subsection{5.7 Contrôle de la prime de fonctions et de résultats
(PFR)}\label{controle-de-la-prime-de-fonctions-et-de-resultats-pfr}}

\href{../Docs/Notices/fiche_PFR.odt}{\includegraphics{icones/Notice.png}}

~\emph{Tableau 5.7.1 : Cumul PFR/IFTS}

48 attributaires PFR sont des non-titulaires. 4 attributaires de PFR ne
sont pas identifiés en categorie A .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes PFR & Agents cumulant PFR et IFTS\tabularnewline
\midrule
\endhead
636.01 636.02 636.03 636.01 R 636.02 R 636.03 R & 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.7.2 : Cumuls PFR/IFTS}

Pas de cumuls.

\href{../Bases/Reglementation/PFR.non.catA.csv}{Lien vers la base de
données PFR non cat.A}\\
\href{../Bases/Reglementation/PFR.non.tit.csv}{Lien vers la base de données
PFR non tit}

4 attributaires ISS sont des non-titulaires. 1 attributaires de ISS ne
sont pas identifiés en categorie A B . 48 attributaires PFR sont des
non-titulaires. 4 attributaires de PFR ne sont pas identifiés en
categorie A .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes PFR & Agents cumulant PFR et ISS\tabularnewline
\midrule
\endhead
636.01 636.02 636.03 636.01 R 636.02 R 636.03 R & 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.7.3 : Cumul PFR/ISS}

Pas de cumuls.

Tous les attributaires de IEMP sont titulaires ou stagiaires. Tous les
attributaires de IEMP sont identifiés en categorie A B C . 48
attributaires PFR sont des non-titulaires. 4 attributaires de PFR ne
sont pas identifiés en categorie A .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes PFR & Agents cumulant PFR et IEMP\tabularnewline
\midrule
\endhead
636.01 636.02 636.03 636.01 R 636.02 R 636.03 R & 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.7.4 : Cumul PFR/IEMP}

Pas de cumuls.

~\emph{Tableau 5.7.5 : Rappel des plafonds annuels de la PFR}

\begin{longtable}[]{@{}ccccc@{}}
\toprule
Adm. général & Adm. HC & Adm. & Direct./Attaché princ. & Secr.
mairie/Attaché\tabularnewline
\midrule
\endhead
58 800 & 55 200 & 49 800 & 25 800 & 20 100\tabularnewline
\bottomrule
\end{longtable}

Les plafonds annuels de la PFR sont dépassés pour 105 cumuls annuels.

\begin{longtable}[]{@{}rrrrr@{}}
\toprule
Matricule & Annee & PFR\_annuel & nb.mois & Grade\tabularnewline
\midrule
\endhead
10151 & 2015 & 65319,92 & 12 & ADMINISTRATEUR HORS CLASSE\tabularnewline
10161 & 2015 & 40071,60 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
1024 & 2015 & 27909,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
10425 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
10664 & 2015 & 25824,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
10665 & 2015 & 33397,80 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
10691 & 2015 & 35567,46 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
1070 & 2015 & 27009,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
10957 & 2015 & 32797,80 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
1104 & 2015 & 25824,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
1142 & 2015 & 39060,00 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
11464 & 2015 & 21540,62 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
1154 & 2015 & 40971,60 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
1158 & 2015 & 24600,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
11624 & 2015 & 25824,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
1163 & 2015 & 48852,00 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
1173 & 2015 & 110400,00 & 12 & ADMINISTRATEUR HORS CLASSE\tabularnewline
1189 & 2015 & 63019,92 & 12 & ADMINISTRATEUR HORS CLASSE\tabularnewline
1191 & 2015 & 32481,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
11986 & 2015 & 22084,56 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
12099 & 2015 & 45792,00 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
1212 & 2015 & 63019,92 & 4 & ADMINISTRATEUR HORS CLASSE\tabularnewline
12262 & 2015 & 39974,40 & 5 & ATTACHÉ PRINCIPAL\tabularnewline
12406 & 2015 & 63019,92 & 12 & ADMINISTRATEUR HORS CLASSE\tabularnewline
1243 & 2015 & 27474,00 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
12583 & 2015 & 63019,92 & 12 & ADMINISTRATEUR HORS CLASSE\tabularnewline
12688 & 2015 & 25224,00 & 5 & ATTACHÉ TERRITORIAL\tabularnewline
13059 & 2015 & 63019,92 & 12 & ADMINISTRATEUR HORS CLASSE\tabularnewline
13093 & 2015 & 23962,80 & 4 & ATTACHÉ TERRITORIAL\tabularnewline
13142 & 2015 & 22740,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
135 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
13531 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
13609 & 2015 & 25224,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
13693 & 2015 & 50050,92 & 12 & ADMINISTRATEUR\tabularnewline
13790 & 2015 & 25224,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
13859 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
140 & 2015 & 27009,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
14101 & 2015 & 50836,03 & 5 & ADMINISTRATEUR HORS CLASSE\tabularnewline
14106 & 2015 & 23962,80 & 4 & ATTACHÉ TERRITORIAL\tabularnewline
1468 & 2015 & 22815,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
151 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
1533 & 2015 & 24609,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
1553 & 2015 & 65319,92 & 12 & ADMINISTRATEUR HORS CLASSE\tabularnewline
1556 & 2015 & 35118,62 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
156 & 2015 & 47952,00 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
1562 & 2015 & 63019,92 & 12 & ADMINISTRATEUR HORS CLASSE\tabularnewline
1563 & 2015 & 26652,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
157 & 2015 & 44097,60 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
159 & 2015 & 46474,80 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
1596 & 2015 & 46367,20 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
1605 & 2015 & 22084,56 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
1647 & 2015 & 44532,00 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
165 & 2015 & 45717,60 & 5 & DIRECTEUR TERRITORIAL\tabularnewline
1679 & 2015 & 22084,56 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
174 & 2015 & 42297,60 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
1795 & 2015 & 46076,36 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
1855 & 2015 & 41397,60 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
1913 & 2015 & 27009,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
1914 & 2015 & 40071,60 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
1923 & 2015 & 42084,60 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
196 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
2 & 2015 & 43197,60 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
214 & 2015 & 27009,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
216 & 2015 & 40071,62 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
240 & 2015 & 40971,62 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
30 & 2015 & 24693,74 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
301 & 2015 & 20191,38 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
391 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
4 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
403 & 2015 & 43197,60 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
43 & 2015 & 22684,56 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
51 & 2015 & 22084,56 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
5482 & 2015 & 24680,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
5565 & 2015 & 47916,96 & 6 & ATTACHÉ PRINCIPAL\tabularnewline
5570 & 2015 & 23733,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
581 & 2015 & 22379,28 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
586 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
618 & 2015 & 28374,00 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
71 & 2015 & 44674,80 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
743 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
754 & 2015 & 40071,60 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
807 & 2015 & 43197,60 & 12 & DIRECTEUR TERRITORIAL\tabularnewline
808 & 2015 & 27009,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
822 & 2015 & 36891,24 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
837 & 2015 & 25824,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
847 & 2015 & 26109,12 & 5 & ATTACHÉ PRINCIPAL\tabularnewline
882 & 2015 & 29280,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
8898 & 2015 & 39171,60 & 4 & ATTACHÉ PRINCIPAL\tabularnewline
8928 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
8966 & 2015 & 37133,72 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
8969 & 2015 & 25824,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
9031 & 2015 & 27009,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
9062 & 2015 & 25824,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
9063 & 2015 & 27009,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
9163 & 2015 & 40071,60 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
9272 & 2015 & 23279,28 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
9274 & 2015 & 27909,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
9319 & 2015 & 37273,60 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
9404 & 2015 & 25224,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
9412 & 2015 & 27009,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
9451 & 2015 & 40971,60 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
949 & 2015 & 27252,00 & 12 & ATTACHÉ TERRITORIAL\tabularnewline
953 & 2015 & 26109,12 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
9585 & 2015 & 47592,00 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
963 & 2015 & 23150,70 & 12 & ATTACHÉ PRINCIPAL\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.7.6 : Valeurs de l'agrégat annuel (PFR ou IFTS) pour
les bénéficiaires de la PFR}

\href{../Bases/Remunerations/beneficiaires.PFR.IFTS.csv}{Lien vers la base
de données agrégat PFR-IFTS}

~\emph{Tableau 5.7.7 : Variations de l'agrégat mensuel moyen (PFR ou
IFTS) pour les bénéficiaires de la PFR}

\hypertarget{controle-de-la-prime-de-service-et-de-rendement-psr}{%
\subsection{5.8 Contrôle de la prime de service et de rendement
(PSR)}\label{controle-de-la-prime-de-service-et-de-rendement-psr}}

2 attributaires PSR sont des non-titulaires. 1 attributaires de PSR ne
sont pas identifiés en categorie A B .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes PSR & Agents cumulant PSR et IFTS\tabularnewline
\midrule
\endhead
534.01 534.01 R 535.00 & 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.8.1 : Cumul PSR/IFTS}

Pas de cumuls.

\href{../Bases/Reglementation/PSR.non.catAB.csv}{Lien vers la base de
données PSR grade non conforme}\\
\href{../Bases/Reglementation/PSR.non.tit.csv}{Lien vers la base de données
PSR non tit}

~\emph{Tableau 5.8.2 : Valeurs de l'agrégat annuel (PSR ou IFTS) pour
les bénéficiaires de la PSR}

\href{../Bases/Remunerations/beneficiaires.PSR.IFTS.csv}{Lien vers la base
de données agrégat PSR-IFTS}

~\emph{Tableau 5.8.3 : Variations de l'agrégat mensuel moyen (PSR ou
IFTS) pour les bénéficiaires de la PSR}

2 attributaires PSR sont des non-titulaires. 1 attributaires de PSR ne
sont pas identifiés en categorie A B .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes PSR & Agents cumulant PSR et IAT\tabularnewline
\midrule
\endhead
534.01 534.01 R 535.00 & 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.8.4 : Cumul PSR/IAT}

Pas de cumuls.

~\emph{Tableau 5.8.5 : Valeurs de l'agrégat annuel (PSR ou IAT) pour les
bénéficiaires de la PSR}

\href{../Bases/Remunerations/beneficiaires.PSR.IAT.csv}{Lien vers la base
de données agrégat PSR-IAT}

~\emph{Tableau 5.8.6 : Variations de l'agrégat mensuel moyen (PSR ou
IAT) pour les bénéficiaires de la PSR}

\hypertarget{controle-de-lindemnite-de-performance-et-de-fonctions-ipf}{%
\subsection{5.9 Contrôle de l'indemnité de performance et de fonctions
(IPF)}\label{controle-de-lindemnite-de-performance-et-de-fonctions-ipf}}

Tous les attributaires de IPF sont titulaires ou stagiaires. Tous les
attributaires de IPF sont identifiés en categorie A .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes IPF & Agents cumulant IPF et IFTS\tabularnewline
\midrule
\endhead
& 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.9.1 : Cumul IPF/IFTS}

Pas de cumuls.

Tous les attributaires de IPF sont titulaires ou stagiaires. Tous les
attributaires de IPF sont identifiés en categorie A .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes IPF & Agents cumulant IPF et PFR\tabularnewline
\midrule
\endhead
& 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.9.2 : Cumul IPF/PFR}

Pas de cumuls.

Tous les attributaires de IPF sont titulaires ou stagiaires. Tous les
attributaires de IPF sont identifiés en categorie A .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes IPF & Agents cumulant IPF et ISS\tabularnewline
\midrule
\endhead
& 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.9.3 : Cumul IPF/ISS}

Pas de cumuls.

~\emph{Tableau 5.9.4 : Valeurs de l'agrégat annuel (IPF ou IFTS) pour
les bénéficiaires de l'IPF}

~\emph{Tableau 5.9.5 : Variations de l'agrégat mensuel moyen (IPF ou
IFTS) pour les bénéficiaires de l'IPF}

\hypertarget{controle-du-rifseep-ifse}{%
\subsection{5.10 Contrôle du RIFSEEP
(IFSE)}\label{controle-du-rifseep-ifse}}

\emph{Pour tirer pleinement profit de ces fonctionnalités, il est
préférable de faire remplir, par les organismes contrôlés le tableau CSV
accessible dans le bloc} \textbf{IFSE} \emph{de l'onglet Extra de
l'application graphique, ou bien à ce lien. Voir aussi la notice} ~
\href{../Docs/Notices/fiche_tableau_ifse.odt}{\includegraphics{icones/Notice.png}}

Tous les attributaires de IFSE sont titulaires ou stagiaires. Tous les
attributaires de IFSE sont identifiés en categorie A B C .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes IFSE & Agents cumulant IFSE et IFTS\tabularnewline
\midrule
\endhead
& 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.10.1 : Cumul IFSE/IFTS}

Pas de cumuls.

~\emph{Tableau 5.10.2 : Cumul IFSE/IAT}

Tous les attributaires de IFSE sont titulaires ou stagiaires. Tous les
attributaires de IFSE sont identifiés en categorie A B C .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes IFSE & Agents cumulant IFSE et IAT\tabularnewline
\midrule
\endhead
& 0\tabularnewline
\bottomrule
\end{longtable}

Pas de cumuls.

4 attributaires ISS sont des non-titulaires. 1 attributaires de ISS ne
sont pas identifiés en categorie A B . Tous les attributaires de IFSE
sont titulaires ou stagiaires. Tous les attributaires de IFSE sont
identifiés en categorie A B C .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes IFSE & Agents cumulant IFSE et ISS\tabularnewline
\midrule
\endhead
& 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.10.3 : Cumul IFSE/ISS}

Pas de cumuls.

Tous les attributaires de IEMP sont titulaires ou stagiaires. Tous les
attributaires de IEMP sont identifiés en categorie A B C . Tous les
attributaires de IFSE sont titulaires ou stagiaires. Tous les
attributaires de IFSE sont identifiés en categorie A B C .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes IFSE & Agents cumulant IFSE et IEMP\tabularnewline
\midrule
\endhead
& 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.10.4 : Cumul IFSE/IEMP}

Pas de cumuls.

Tous les attributaires de PFI sont titulaires ou stagiaires. Tous les
attributaires de PFI sont identifiés en categorie A B C . Tous les
attributaires de IFSE sont titulaires ou stagiaires. Tous les
attributaires de IFSE sont identifiés en categorie A B C .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes IFSE & Agents cumulant IFSE et PFI\tabularnewline
\midrule
\endhead
& 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.10.5 : Cumul IFSE/PFI}

Pas de cumuls.

Tous les attributaires de IFSE sont titulaires ou stagiaires. Tous les
attributaires de IFSE sont identifiés en categorie A B C .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes IFSE & Agents cumulant IFSE et PSR\tabularnewline
\midrule
\endhead
& 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.10.6 : Cumul IFSE/PSR}

Pas de cumuls.

Tous les attributaires de IFSE sont titulaires ou stagiaires. Tous les
attributaires de IFSE sont identifiés en categorie A B C .

\begin{longtable}[]{@{}cc@{}}
\toprule
Codes IFSE & Agents cumulant IFSE et PFR\tabularnewline
\midrule
\endhead
& 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.10.7 : Cumul IFSE/PFR}

Pas de cumuls.

Le fichier des plafonds de l'IFSE n'est pas importé. Le test du respect
des plafonds ne peut donc pas être effectué. Le lien ci-après est
inactif.

~\emph{Tableau 5.10.8 : Coûts des dépassements de plafond IFSE}

Pas d'analyse des plafonds IFSE.

~\emph{Tableau 5.10.9 : Valeurs de l'agrégat annuel (IFSE ou PFR) pour
les bénéficiaires de l'IFSE}

~\emph{Tableau 5.10.10 : Variations de l'agrégat mensuel moyen (IFSE ou
PFR) pour les bénéficiaires de l'IFSE}

\hypertarget{controle-de-la-prime-de-fonctions-informatiques-pfi}{%
\subsection{5.2 Contrôle de la prime de fonctions informatiques
(PFI)}\label{controle-de-la-prime-de-fonctions-informatiques-pfi}}

\href{../Docs/Notices/fiche_PFI.odt}{\includegraphics{icones/Notice.png}}

aucune

\hypertarget{controle-des-vacations-horaires-pour-les-fonctionnaires}{%
\subsection{5.3 Contrôle des vacations horaires pour les
fonctionnaires}\label{controle-des-vacations-horaires-pour-les-fonctionnaires}}

Les fonctionnaires peuvent effectuer des vacations horaires pour leur
propre employeur à condition de bénéficier d'une autorisation de cumul
d'activité accessoire et que les activités concernées ne fassent pas
partie du service normal. Les cumuls détectés ci-dessous se limitent aux
cas de vacations horaires détectées. L'existence des pièces
justificatives pourra être recherchée.

Pas de vacation détectée.

\hypertarget{controles-sur-les-contractuels-effectuant-des-vacations-horaires}{%
\subsection{5.4 Contrôles sur les contractuels effectuant des vacations
horaires}\label{controles-sur-les-contractuels-effectuant-des-vacations-horaires}}

\href{../Docs/Notices/fiche_CEV_droit.odt}{\includegraphics{icones/Notice.png}}

\textbf{Attention}\\
Les contrôles réalisés sur les payes des vacataires nécessitent, le plus
souvent, la saisie des codes de paye relatifs aux vacations dans
l'onglet Codes de l'interface graphique, en raison du fréquent mauvais
renseignement de ces codes en base de paye. ~
\href{../Docs/Notices/fiche_onglet_codes.odt}{\includegraphics{icones/Notice.png}}

~\emph{Tableau 5.4.1 : Contractuels effectuant des vacations horaires
(CEV)} ~
\href{../Docs/Notices/fiche_CEV_horaires.odt}{\includegraphics{icones/Notice.png}}

\begin{longtable}[]{@{}cc@{}}
\toprule
Nombre de CEV & Nombre de lignes indemnitaires payees\tabularnewline
\midrule
\endhead
0 & 0\tabularnewline
\bottomrule
\end{longtable}

~\emph{Tableau 5.4.2 : CEV percevant le supplément familial de
traitement ou l'indemnité de résidence} ~
\href{../Docs/Notices/fiche_CEV_SFT.odt}{\includegraphics{icones/Notice.png}}

\begin{longtable}[]{@{}cc@{}}
\toprule
Nombre d'agents concernés & Nombre de lignes de paye
SFT/IR\tabularnewline
\midrule
\endhead
0 & 0\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{controle-sur-les-logements-par-necessite-absolue-de-service-nas}{%
\subsection{5.5 Contrôle sur les logements par nécessité absolue de
service
(NAS)}\label{controle-sur-les-logements-par-necessite-absolue-de-service-nas}}

\href{../Docs/Notices/fiche_NAS.odt}{\includegraphics{icones/Notice.png}}\\
\emph{Pour que le logiciel puisse contrôler sans risque d'erreur les
concessions de logement, il est nécessaire de faire remplir, par les
organismes contrôlés le tableau CSV accessible dans le bloc}
\textbf{Logement} \emph{de l'onglet Extra de l'application graphique, ou
bien à ce lien. Voir aussi la notice} ~
\href{../Docs/Notices/fiche_tableau_logements.odt}{\includegraphics{icones/Notice.png}}

\textbf{Contrôle sur les logements par NAS}

Pas de logement par NAS déclaré dans le fichier de l'onglet Extra mais
non déclaré en base de paye\\
Pas de logement par NAS déclaré en base de paye mais non déclaré dans le
fichier importé par l'onglet Extra

\hypertarget{controle-sur-les-indemnites-des-elus}{%
\subsection{5.13 Contrôle sur les indemnités des
élus}\label{controle-sur-les-indemnites-des-elus}}

\begin{longtable}[]{@{}llrlrrr@{}}
\toprule
Matricule & Nom & Annee & Emploi & Indemnités & Autres &
Total\tabularnewline
\midrule
\endhead
ABRIAT & 11558 & 2015 & Conservateur du Patrimoine & 73859,16 & 0 &
94109,48\tabularnewline
LASSALLE & 11623 & 2015 & Conservateur du Patrimoine & 93871,98 & 0 &
120847,98\tabularnewline
PAPIN & 13087 & 2015 & Conservateur du Patrimoine & 66763,20 & 0 &
82519,20\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Reglementation/remunerations.elu.csv}{Lien vers la base de
données Rémunérations des élus}

\hypertarget{lien-avec-le-compte-de-gestion}{%
\subsection{5.14 Lien avec le compte de
gestion}\label{lien-avec-le-compte-de-gestion}}

\emph{Pour tirer pleinement profit de ces fonctionnalités, il est
préférable de faire remplir, par les organismes contrôlés le tableau CSV
accessible dans le bloc} \textbf{Bugdet} \emph{de l'onglet Extra de
l'application graphique, ou bien à ce lien. Voir aussi la notice} ~
\href{../Docs/Notices/fiche_tableau_budget.odt}{\includegraphics{icones/Notice.png}}

La correspondance avec le compte de gestion ne peut pas être établie
réigoureusement sans le fichier de correspondance paye-budget (voir
onglet Extra).

\emph{Avertissement : les rappels comprennent également les rappels de
cotisations et déductions diverses.}

\hypertarget{controle-du-supplement-familial-de-traitement}{%
\subsection{5.15 Contrôle du supplément familial de
traitement}\label{controle-du-supplement-familial-de-traitement}}

\href{../Docs/Notices/fiche_SFT.odt}{\includegraphics{icones/Notice.png}}

Pour les agents n'ayant pas d'enfant signalé en base, il a été détecté 1
bulletin de paie présentant un paiement du SFT apparemment anormal.

\href{../Bases/Reglementation/Paie.sans.enfant.reduit.csv}{Lien vers la
base des paiements de SFT à agents sans enfant signalé}

Pour les agents ayant au moins un enfant, il a été détecté 10865
bulletins de paie présentant un écart de paiement du SFT supérieur à 1
euro.

\href{../Bases/Reglementation/controle.sft.csv}{Lien vers la base des
écarts de paiement sur SFT}

\hypertarget{controle-des-cotisations-de-retraite}{%
\subsection{5.16 Contrôle des cotisations de
retraite}\label{controle-des-cotisations-de-retraite}}

\href{../Docs/Notices/fiche_retraite.odt}{\includegraphics{icones/Notice.png}}\\
\textbf{Non titulaires}

Les non titulaires ne doivent pas cotiser à la CNRACL.

~\emph{Tableau 5.16.1 : Cotisations irrégulières à la CNRACL}

Des cotisations CNRACL sont versées pour des agents non titulaires : 364
lignes de paye.

\begin{longtable}[]{@{}cc@{}}
\toprule
Cotisations salarié & Cotisations employeur\tabularnewline
\midrule
\endhead
49 716,82 & 158 949,1\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Reglementation/Cotisations.irreg.csv}{Lien vers la base des
cotisations irrégulières}

\textbf{Titulaires}

Les titulaires ne doivent pas cotiser à l'IRCANTEC.

~\emph{Tableau 5.16.2 : Cotisations irrégulières à l'IRCANTEC}

Des cotisations IRCANTEC sont versées pour des agents titulaires : 4
lignes de paye.

\begin{longtable}[]{@{}cc@{}}
\toprule
Cotisations salarié & Cotisations employeur\tabularnewline
\midrule
\endhead
49,3 & 73,96\tabularnewline
\bottomrule
\end{longtable}

\href{../Bases/Reglementation/Cotisations.irreg.ircantec.csv}{Lien vers la
base des cotisations irrégulières}

\hypertarget{primes-de-la-fonction-publique-hospitaliere}{%
\subsection{5.17 Primes de la fonction publique
hospitalière}\label{primes-de-la-fonction-publique-hospitaliere}}

\href{../Docs/Notices/fiche_FPH.odt}{\includegraphics{icones/Notice.png}}

\emph{Les primes qui suivent ne peuvent être octroyées qu'à des
fontionnaires.}\\
\emph{Les tests portent sur les cas d'attribution à des non-titulaires
(et autres statuts)}

\textbf{Prime spécifique}

Ce contrôle ne porte pas sur la FPH. Les liens hypertextes ci-dessous
seront désactivés.\\
Pour activer le contrôle FPH, cocher la case correspondante de l'onglet
\textbf{Options \textgreater{} Format} de l'interface graphique\\
Prime spécifique Non traité.

\textbf{Prime de technicité}

Ce contrôle ne porte pas sur la FPH. Les liens hypertextes ci-dessous
seront désactivés.\\
Pour activer le contrôle FPH, cocher la case correspondante de l'onglet
\textbf{Options \textgreater{} Format} de l'interface graphique\\
Primes de technicité Non traité.

\textbf{Indemnité forfaitaire et technique}

Ce contrôle ne porte pas sur la FPH. Les liens hypertextes ci-dessous
seront désactivés.\\
Pour activer le contrôle FPH, cocher la case correspondante de l'onglet
\textbf{Options \textgreater{} Format} de l'interface graphique

Indemnité forfaitaire et technique Non traité.

\textbf{Prime de service}

Ce contrôle ne porte pas sur la FPH. Les liens hypertextes ci-dessous
seront désactivés.\\
Pour activer le contrôle FPH, cocher la case correspondante de l'onglet
\textbf{Options \textgreater{} Format} de l'interface graphique

Primes de service Non traité.

\newpage

\hypertarget{annexe}{%
\section{Annexe}\label{annexe}}

\hypertarget{controle-des-evenements-de-paye}{%
\subsection{Contrôle des événements de
paye}\label{controle-des-evenements-de-paye}}

\href{../Bases/Fiabilite/Evenements.csv}{Lien vers la nomenclature des
événements de paye}\\
\href{../Bases/Fiabilite/Evenements.ind.csv}{Tri par type d'évement, agent,
année, mois}\\
\href{../Bases/Fiabilite/Evenements.mat.csv}{Tri par agent, année, mois,
événement}

\hypertarget{codes-et-libelles-de-paye}{%
\subsection{Codes et libellés de paye}\label{codes-et-libelles-de-paye}}

\href{../Docs/Notices/fiche_individualisation.odt}{\includegraphics{icones/Notice.png}}

Certains libellés ou codes de paye peuvent être équivoques et entraîner
des erreurs de requête.\\
Les liens ci-après donnent les codes correspondant à au moins deux
libellés distincts, les libellés correspondant à au moins deux codes et
les codes ou libellés correspondant à au moins deux types de ligne de
paye distincts.\\
L'association d'un même code à plusieurs libellés de paye peut induire
des erreurs d'analyse comptable et financière lorsque les libellés
correspondent à des types de ligne de paye distincts.

\href{../Bases/Fiabilite/code.libelle.short.csv}{Lien vers la table
Codes/Libelles pour l'onglet Codes}\\
\href{../Bases/Fiabilite/code.libelle.csv}{Lien vers la table
Codes/Libelles pour appariement avec les balances}

\hypertarget{doublons}{%
\subsection{Doublons}\label{doublons}}

Attention : Altaïr a détecté des lignes dupliquées alors qu'aucun
retraitement des lignes dupliquées n'est prévu par défaut.

\hypertarget{fiabilite-des-heures-et-des-quotites-de-travail}{%
\subsection{Fiabilite des heures et des quotités de
travail}\label{fiabilite-des-heures-et-des-quotites-de-travail}}

Nombre de bulletins : 84 106

Les heures de travail ont été redressées avec la méthode des quotités.
La méthode des quotités ne s'applique pas aux élus, vacataires et
assistantes maternelles détectés. Pour les autres agents, si la quotité
de temps de travail est non nulle, la méthode redresse le nombre
d'heures réalisées à partir du nombre d'heures normal à temps plein
lorsqu'une quotité de temps de travail est aussi indiquée.

Nombre de bulletins de paie redressés : 1 132

Pourcentage de redressements : 1,35 \% des bulletins de paie.

Pourcentage d'heures renseignées (après redressement éventuel): 99,5 \%

Pourcentage de quotités renseignées : 99,3 \%

Nombre de bulletins à heures et quotités : 83544 {[} 99,3 \%{]}

Nombre de bulletins à heures sans quotités : 104 {[} 0,1 \%{]}

Nombre de bulletins à quotités sans heures : 0 {[} 0 \%{]}

Nombre de bulletins apparemment inactifs : 458 {[} 0,5 \%{]}

Nombre de bulletins de paie de salaires versés pour un champ Heures = 0
: 294 {[} 0,5 \%{]}

\href{../Bases/Fiabilite/base.heures.nulles.salaire.nonnull.csv}{Lien vers
la base de données des salaires versés pour Heures=0}

\hypertarget{tableau-des-personnels}{%
\subsection{Tableau des personnels}\label{tableau-des-personnels}}

\emph{Pour vérifier que le logiciel déduit correctement les categories
statutaires des libellés de grade, il est préférable de faire remplir,
par les organismes contrôlés le tableau CSV accessible dans le bloc}
\textbf{Grade et categorie statutaire} \emph{de l'onglet Extra de
l'application graphique, ou bien à ce lien. Voir aussi la notice} ~
\href{../Docs/Notices/fiche_tableau_categories.odt}{\includegraphics{icones/Notice.png}}

\href{../Bases/Effectifs/grades.categories.csv}{Lien vers la base des
grades et categories}

\href{../Bases/Effectifs/matricules.csv}{Lien vers la base des personnels}
