// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_sft
double rcpp_sft(int prop, const std::string& indice, double nbi, double duree, int annee, int mois);
RcppExport SEXP SFT_rcpp_sft(SEXP propSEXP, SEXP indiceSEXP, SEXP nbiSEXP, SEXP dureeSEXP, SEXP anneeSEXP, SEXP moisSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type prop(propSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type indice(indiceSEXP);
    Rcpp::traits::input_parameter< double >::type nbi(nbiSEXP);
    Rcpp::traits::input_parameter< double >::type duree(dureeSEXP);
    Rcpp::traits::input_parameter< int >::type annee(anneeSEXP);
    Rcpp::traits::input_parameter< int >::type mois(moisSEXP);
    __result = Rcpp::wrap(rcpp_sft(prop, indice, nbi, duree, annee, mois));
    return __result;
END_RCPP
}
