# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sft <- function(prop, indice, nbi, duree, annee, mois) {
    .Call('suppfam_sft', PACKAGE = 'suppfam', prop, indice, nbi, duree, annee, mois)
}

